int KilledOracle = 0;
int AwakenSpectres = 0;
int SpectreTarget;

#define ACCURACYCOUNT 10
#define SIGILCOUNT    5

int SigilSplinters[SIGILCOUNT][2] = 
{
    {"SigilSplinter1", "SigilSplinter1Temp"},
    {"SigilSplinter2", "SigilSplinter2Temp"},
    {"SigilSplinter3", "SigilSplinter3Temp"},
    {"SigilSplinter4", "SigilSplinter4Temp"},
    {"SigilSplinter5", "SigilSplinter5Temp"},
};

int SpectralTogglers[SIGILCOUNT] = 
{
    "SigilInventoryWeapon1",
    "SigilInventoryWeapon2",
    "SigilInventoryWeapon3",
    "SigilInventoryWeapon4",
    "SigilInventoryWeapon5",
};

int BeaconMonsters[CLASSCOUNT] = 
{
    "FriendlyDoomImp",
    "FriendlyFlemoid",
    "FriendlyNitrogolem",
    "FriendlyNazi",
    "FriendlyAfrit",
    "FriendlyAlienTrooper",
    "FriendlyPfhorTrooper",
    "FriendlyGrunt",
    "FriendlyLowGuard",
    "FriendlySectorPatrol",
    "FriendlyBrownCultist",
    "FriendlySuperRebelSpawner",        
    "FriendlyHSD",
    "FriendlyAnimatedProbe",
    "FriendlyUNBluesuit",
    "FriendlyStarTrooper",
    "FriendlyRobotGuard", //+Added
    "FriendlyTerroristDroid", //+Added
    "FriendlyMinoDrake", //+Added
    "FriendlyBarney", //+Added
    "FriendlyFatAss", //+Added
    "FriendlyCMTrooper", //+Added
    "FriendlyAnubisWarrior", //+Added
    "FriendlyTurdMinion", //+Added
    "FriendlyRobotGuard", //+Added
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
};

str AccuracyUniques[CLASSCOUNT][UNIQUECOUNT] =
{
    {"DoomStrifeUnique1",             "DoomStrifeUnique2",      "DoomStrifeUnique3"},
    {"ChexSoulsphere",                "ChexStrifeUnique2",      ""},
    {"CorvusStrifeUnique1",           "SamsaraCorvusArtiEgg",   ""},
    {"WolfStrifeUnique1",             "WolfStrifeUnique2",      "WolfStrifeUnique3"},
    {"HexenStrifeUnique1",            "HexenStrifeUnique2",     "HexenStrifeUnique3"},
    {"DukeStrifeUnique1",             "DukeStrifeUnique2",      "DukeStrifeUnique3"},
    {"MarathonStrifeUnique1",         "MarathonStrifeUnique2",  ""},
    {"RangerStrifeUnique",            "",                       ""},
    {"ROTTStrifeUnique1",             "ROTTStrifeUnique2",      ""},
    {"BlakeRefill",                   "",                       ""},
    {"VoodooDoll",                    "CalebStrifeUnique2",     "CalebStrifeUnique3"},
    {"StrifeguyStrifeUnique",         "",                       ""},
    {" Eradicator Enhancement Chip ", "",                       ""},
    {"C7StrifeUnique",                "",                       ""},
    {"RMRJetPack",                    "",                       ""},
    {"KatarnSupercharge",             "",                       ""},
    {"IPOGStrifeUnique",              "",                       ""},
    {"JackStrifeUnique",              "",                       ""},
    {"WTStrengthPhial",               "",                       ""},
    {"HalfLifeStrifeUnique1",         "HalfLifeStrifeUnique2",  "HalfLifeStrifeUnique3"},
    {"SWRipperHeart",                 "HeatSeekingCard",        "SWGasGrenade"},
    {"CyberMageStrifeUnique",         "",                       ""},
    {"JonStrifeUnique",               "",                       ""},
    {"LeonardStrifeUnique1",          " Chicken Crossbow ",     ""}, // chicken crossbow is given as ammo instead of a weapon
    {"BittermanStrifeUnique1",        "BittermanStrifeUnique2", "BittermanStrifeUnique3"},
    {"Hexen2TomeOfPower",             "Hexen2ForceCube",        ""},
    {"BondStrifeUnique1",             "BondStrifeUnique2",      "BondStrifeUnique3"},
    {"Catacomb_RandomGemStrife",      "",                       ""},
    {"Painkiller_Tarot_SilverGiver",  "",                       ""},
    {"UnrealStrifeUnique1",           "UnrealStrifeUnique2",    "UnrealStrifeUnique3"},
    {"RTCWStrifeUnique1",             "RTCWStrifeUnique2",      "RTCWStrifeUnique3"},
    {"Quake3StrifeUnique1",           "Quake3StrifeUnique2",    "Quake3StrifeUnique3"},
    {"DescentStrifeUnique1",          "DescentStrifeUnique2",   "DescentQuadLaser"},
    {"DeusEx_LAW",                    "DeusExStrifeUnique2",    "DeusEx_NanoSword"},
};

int DoomAccuracyZerks[ACCURACYCOUNT] = 
{
    "DoomguyStrifeZerk1",
    "DoomguyStrifeZerk2",
    "DoomguyStrifeZerk3",
    "DoomguyStrifeZerk4",
    "DoomguyStrifeZerk5",
    "DoomguyStrifeZerk6",
    "DoomguyStrifeZerk7",
    "DoomguyStrifeZerk8",
    "DoomguyStrifeZerk9",
    "DoomguyStrifeZerk0"
};

str AccuracyMessages[CLASSCOUNT][MAXMODES][UNIQUECOUNT][LOADOUTCOUNT][MSGCOUNT] =
{
    {
        {
            {{
                "You grow more berserk.",
                "You're not actually getting angrier. You're just punching more accurately.",
                "Fuck your accuracy training shit!",
                "Yes... Channel your anger...",
                "How does that even work?",
                "Well, if you insist on using your fists...",
                "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
                "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
                "It was a ruse! You were secretly in a boxing match all along!",
                "Don't get too cocky, Mikey.",
            }},
            {{ // x2 due to stronghold
                "You grow more berserk.",
                "You're not actually getting angrier. You're just punching more accurately.",
                "Fuck your accuracy training shit!",
                "Yes... Channel your anger...",
                "How does that even work?",
                "Well, if you insist on using your fists...",
                "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
                "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
                "It was a ruse! You were secretly in a boxing match all along!",
                "Don't get too cocky, Mikey.",
            }},
            {{ // x3 due to stronghold
                "You grow more berserk.",
                "You're not actually getting angrier. You're just punching more accurately.",
                "Fuck your accuracy training shit!",
                "Yes... Channel your anger...",
                "How does that even work?",
                "Well, if you insist on using your fists...",
                "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
                "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
                "It was a ruse! You were secretly in a boxing match all along!",
                "Don't get too cocky, Mikey.",
            }},
        },
        {
            {{
                "You grow more berserk.",
                "You're not actually getting angrier. You're just punching more accurately.",
                "Fuck your accuracy training shit!",
                "Yes... Channel your anger...",
                "How does that even work?",
                "Well, if you insist on using your fists...",
                "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
                "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
                "It was a ruse! You were secretly in a boxing match all along!",
                "Don't get too cocky, Mikey.",
            }},
            {{ // x2 due to stronghold
                "You grow more berserk.",
                "You're not actually getting angrier. You're just punching more accurately.",
                "Fuck your accuracy training shit!",
                "Yes... Channel your anger...",
                "How does that even work?",
                "Well, if you insist on using your fists...",
                "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
                "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
                "It was a ruse! You were secretly in a boxing match all along!",
                "Don't get too cocky, Mikey.",
            }},
            {{ // x3 due to stronghold
                "You grow more berserk.",
                "You're not actually getting angrier. You're just punching more accurately.",
                "Fuck your accuracy training shit!",
                "Yes... Channel your anger...",
                "How does that even work?",
                "Well, if you insist on using your fists...",
                "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
                "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
                "It was a ruse! You were secretly in a boxing match all along!",
                "Don't get too cocky, Mikey.",
            }},
        },
        {
            {{
                "You grow more berserk.",
                "You're not actually getting angrier. You're just punching more accurately.",
                "Fuck your accuracy training shit!",
                "Yes... Channel your anger...",
                "How does that even work?",
                "Well, if you insist on using your fists...",
                "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
                "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
                "It was a ruse! You were secretly in a boxing match all along!",
                "Don't get too cocky, Mikey.",
            }},
            {{
                "You grow more berserk.",
                "You're not actually getting angrier. You're just punching more accurately.",
                "Fuck your accuracy training shit!",
                "Yes... Channel your anger...",
                "How does that even work?",
                "Well, if you insist on using your fists...",
                "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
                "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
                "It was a ruse! You were secretly in a boxing match all along!",
                "Don't get too cocky, Mikey.",
            }},
            {{
                "You grow more berserk.",
                "You're not actually getting angrier. You're just punching more accurately.",
                "Fuck your accuracy training shit!",
                "Yes... Channel your anger...",
                "How does that even work?",
                "Well, if you insist on using your fists...",
                "I'm sure those reinforced steel robots are trembling over your fleshy hands.",
                "Let's settle this dispute like gentlemen! Or kill each other. Both work.",
                "It was a ruse! You were secretly in a boxing match all along!",
                "Don't get too cocky, Mikey.",
            }},
        },
    },
    {{
        {{
            "Supercharge Breakfast!",
            "OM NOM NOM NOM",
            "Because medikits are for wimps.",
            "Crunchy.",
            "Chex marks the spot!",
            "Is this cannibalism or what?",
            "It's milk you can chew!",
            "Free breakfast with every training!",
            "How generous of him to provide you breakfast, too.",
            "So, uh, where did you get the milk from? The cows are dead.",
        }},
        {{
            "You got the Chain-Lightning Zorcher!",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Grim Ballista",
            "Seriously, you try lifting this thing.",
            "Say, wasn't this an instagib many years ago?",
            "The heartbeat means it's happy to see you.",
            "Death by spittle from sneezing ghosts.",
            "Iiiii aaaam the ghoooost boooolt! WHOOOO!",
            "So haunted, it belongs on eBay.",
            "These ghosts are so angry, they even explode a little bit.",
            "No association with John Grimm.",
            "When there's so many apparitions walking the earth, you use them as ammo.",
        }},
        {{
            "Morph Ovum",
            "Parthoris Fried Chicken.",
            "Because nothing's better than turning a templar harmless.",
            "I'm calling fowl on this.",
            "Don't eat it.",
            "I'm sure there's hundreds of egg puns you can use.",
            "Omelettes, break some eggs, etc.",
            "",
            "",
            "",
        }},
    }},
    {
        {
            {{
                "Extra Life",
                "Maybe now you can go to college.",
                "Works in Zandronum!",
                "One day, the villains will learn how to respawn, too.",
                "Now you can hug a giant metal robot with no repercussions.",
                "Good for the soul, too.",
                "Go ahead, taunt those inquisitors.",
                "Being stopped? \cgNah\c-.",
                "",
                "",
            }},
            {{
                "Ammo Crate",
                "You might as well tape down the fire button at this point.",
                "Pretty much an unstoppable killing machine now. At least until you run out of bullets again.",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
            {{ // x2 due to totenkopf
                "Ammo Crate",
                "You might as well tape down the fire button at this point.",
                "Pretty much an unstoppable killing machine now. At least until you run out of bullets again.",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Extra Life",
                "Maybe now you can go to college.",
                "Works in Zandronum!",
                "One day, the villains will learn how to respawn, too.",
                "Now you can hug a giant metal robot with no repercussions.",
                "Good for the soul, too.",
                "Go ahead, taunt those inquisitors.",
                "Being stopped? \cgNah\c-.",
                "",
                "",
            }},
            {{
                "Ammo Crate",
                "You might as well tape down the fire button at this point.",
                "Pretty much an unstoppable killing machine now. At least until you run out of bullets again.",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
            {{ // x2 due to totenkopf
                "Ammo Crate",
                "You might as well tape down the fire button at this point.",
                "Pretty much an unstoppable killing machine now. At least until you run out of bullets again.",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Flamethrower",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
            {{
                "MG42 Portable Machine Gun",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
            {{
                "Scoped Kar98k Rifle",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
    },
    {
        {
            {{
                "Tome of Power",
                "For a last ditch effort, you can always throw it.",
                "Well, show's over, I guess.",
                "Little known fact: LeVar Burton was actually a wizard.",
                "Only actually seven of these things? Tyketto was a dick for a Seraph.",
                "I didn't play a damn FPS to read!",
                "Death of a thousand papercuts!",
                "Be ye magicked, bitches.",
                "I'm totally going to kick your ass, guys, just let me finish this paragraph.",
                "It's actually a romance novel. The \"power\" refers to something else entirely.",
            }},
            {{
                "Disc of Repulsion",
                "Hey! Personal space, asshole!",
                "Careful not to use it on your friends.",
                "2011 called. It wants its Hexen slot 1 back.",
                "You need to play keep away because your dumbass didn't bring a sword.",
                "The enemies will kill each other if they bump into each other.",
                "",
                "",
                "",
                "",
            }},
            {
                {
                    "Dark Servant",
                    "I am the summoner and the cleric.",
                    "Moo moo, motherfucker!",
                    "Two's a crowd.",
                    "I'm about to clean this place up real quick.",
                    "Hey, it's that one boss from Heretic!",
                    "Beta Ray Bill?",
                    "",
                    "",
                    "",
                },
                {
                    "Porkalator",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
        },
        {
            {{
                "Tome of Power",
                "For a last ditch effort, you can always throw it.",
                "Well, show's over, I guess.",
                "Little known fact: LeVar Burton was actually a wizard.",
                "Only actually seven of these things? Tyketto was a dick for a Seraph.",
                "I didn't play a damn FPS to read!",
                "Death of a thousand papercuts!",
                "Be ye magicked, bitches.",
                "I'm totally going to kick your ass, guys, just let me finish this paragraph.",
                "It's actually a romance novel. The \"power\" refers to something else entirely.",
            }},
            {{
                "Disc of Repulsion",
                "Hey! Personal space, asshole!",
                "Careful not to use it on your friends.",
                "2011 called. It wants its Hexen slot 1 back.",
                "You need to play keep away because your dumbass didn't bring a sword.",
                "The enemies will kill each other if they bump into each other.",
                "",
                "",
                "",
                "",
            }},
            {
                {
                    "Dark Servant",
                    "I am the summoner and the cleric.",
                    "Moo moo, motherfucker!",
                    "Two's a crowd.",
                    "I'm about to clean this place up real quick.",
                    "Hey, it's that one boss from Heretic!",
                    "Beta Ray Bill?",
                    "",
                    "",
                    "",
                },
                {
                    "Porkalator",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
        },
        {
            {{
                "Tome of Power",
                "For a last ditch effort, you can always throw it.",
                "Well, show's over, I guess.",
                "Little known fact: LeVar Burton was actually a wizard.",
                "Only actually seven of these things? Tyketto was a dick for a Seraph.",
                "I didn't play a damn FPS to read!",
                "Death of a thousand papercuts!",
                "Be ye magicked, bitches.",
                "I'm totally going to kick your ass, guys, just let me finish this paragraph.",
                "It's actually a romance novel. The \"power\" refers to something else entirely.",
            }},
            {{
                "Disc of Repulsion",
                "Hey! Personal space, asshole!",
                "Careful not to use it on your friends.",
                "2011 called. It wants its Hexen slot 1 back.",
                "You need to play keep away because your dumbass didn't bring a sword.",
                "The enemies will kill each other if they bump into each other.",
                "",
                "",
                "",
                "",
            }},
            {
                {
                    "Dark Servant",
                    "I am the summoner and the mage.",
                    "Moo moo, motherfucker!",
                    "Two's a crowd.",
                    "I'm about to clean this place up real quick.",
                    "Hey, it's that one boss from Heretic!",
                    "Beta Ray Bill?",
                    "",
                    "",
                    "",
                },
                {
                    "Porkalator",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
        },
        {
            {{
                "Tome of Power",
                "For a last ditch effort, you can always throw it.",
                "Well, show's over, I guess.",
                "Little known fact: LeVar Burton was actually a wizard.",
                "Only actually seven of these things? Tyketto was a dick for a Seraph.",
                "I didn't play a damn FPS to read!",
                "Death of a thousand papercuts!",
                "Be ye magicked, bitches.",
                "I'm totally going to kick your ass, guys, just let me finish this paragraph.",
                "It's actually a romance novel. The \"power\" refers to something else entirely.",
            }},
            {{
                "Disc of Repulsion",
                "Hey! Personal space, asshole!",
                "Careful not to use it on your friends.",
                "2011 called. It wants its Hexen slot 1 back.",
                "You need to play keep away because your dumbass didn't bring a sword.",
                "The enemies will kill each other if they bump into each other.",
                "",
                "",
                "",
                "",
            }},
            {
                {
                    "Dark Servant",
                    "I am the summoner and the fighter.",
                    "Moo moo, motherfucker!",
                    "Two's a crowd.",
                    "I'm about to clean this place up real quick.",
                    "Hey, it's that one boss from Heretic!",
                    "Beta Ray Bill?",
                    "",
                    "",
                    "",
                },
                {
                    "Porkalator",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
        },
    },
    {
        {
            {{
                "Jetpack",
                "I believe I can touch the sky.",
                "Guaranteed to make friends with mappers.",
                "And this is why Virus will never be in.",
                "Because you have that on your sprite for a reason.",
                "Watch your ass, the jet burns.",
                "The gas mileage is \caterrible\c-.",
                "Corvus and the Hexen characters want their Wings of Wrath back.",
                "What's that? You can only move in two dimensions?",
                "And fuck you, too, fall damage.",
            }},
            {{
                "Shrinker!",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
            {{
                "Expander!",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Jetpack",
                "I believe I can touch the sky.",
                "Guaranteed to make friends with mappers.",
                "And this is why Virus will never be in.",
                "Because you have that on your sprite for a reason.",
                "Watch your ass, the jet burns.",
                "The gas mileage is \caterrible\c-.",
                "Corvus and the Hexen characters want their Wings of Wrath back.",
                "What's that? You can only move in two dimensions?",
                "And fuck you, too, fall damage.",
            }},
            {{
                "Shrinker Voodoo Ring!",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
            {{
                "Expander Voodoo Ring!",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Jetpack",
                "I believe I can touch the sky.",
                "Guaranteed to make friends with mappers.",
                "And this is why Virus will never be in.",
                "Because you have that on your sprite for a reason.",
                "Watch your ass, the jet burns.",
                "The gas mileage is \caterrible\c-.",
                "Corvus and the Hexen characters want their Wings of Wrath back.",
                "What's that? You can only move in two dimensions?",
                "And fuck you, too, fall damage.",
            }},
            {{ // x2 due to original/LAB
                "Jetpack",
                "I believe I can touch the sky.",
                "Guaranteed to make friends with mappers.",
                "And this is why Virus will never be in.",
                "Because you have that on your sprite for a reason.",
                "Watch your ass, the jet burns.",
                "The gas mileage is \caterrible\c-.",
                "Corvus and the Hexen characters want their Wings of Wrath back.",
                "What's that? You can only move in two dimensions?",
                "And fuck you, too, fall damage.",
            }},
            {{ // x3 due to original/LAB
                "Jetpack",
                "I believe I can touch the sky.",
                "Guaranteed to make friends with mappers.",
                "And this is why Virus will never be in.",
                "Because you have that on your sprite for a reason.",
                "Watch your ass, the jet burns.",
                "The gas mileage is \caterrible\c-.",
                "Corvus and the Hexen characters want their Wings of Wrath back.",
                "What's that? You can only move in two dimensions?",
                "And fuck you, too, fall damage.",
            }},
        },
    },
    {{
        {{
            "UNKNOWN WEAPON CLASS system error 0xfded",
            "The difference between a room of aliens and a carpet of them.",
            "What fun to watch you work.",
            "~text interface term\ciinal malfunction error \cd~2992dud",
            "your former self destroyed the dreaming way is eased",
            "down to the crushing center and spared the dance of forever",
            "This will allow you to kill more aliens. Does that make you happy?",
            "shedding all the weight of imagined moments and fear",
            "because fear is not the blood",
            "I know who you are.",
        }},
        {{
            "UNKNOWN WEAPON CLASS system error 0xfded",
            "The difference between a room of aliens and a carpet of them.",
            "What fun to watch you work.",
            "~text interface term\ciinal malfunction error \cd~2992dud",
            "your former self destroyed the dreaming way is eased",
            "down to the crushing center and spared the dance of forever",
            "This will allow you to kill more aliens. Does that make you happy?",
            "shedding all the weight of imagined moments and fear",
            "because fear is not the blood",
            "I know who you are.",
        }},
    }},
    {{
        {{
            "You got the Laser Cannon.",
            "If this were in vanilla Quake, it would be slot 6. \ckbut alas",
            "Are any of the weapon designs in Quake even practical?",
            "Do not aim at face. Not that it'll help.",
            "Does it come in blueberry?",
            "What is this, Star Wars?",
            "Bouncy red death!",
            "Pewpewlasers!",
            "Ia ia fhtagn, you flying squash.",
            "Ia ia fhtagn, you floating flower pot.",
        }},
    }},
    {
        {
            {{
                "You picked up the Excalibat.",
                "Baseball time!",
                "Here, catch!",
                "I'm off to a field run.",
                "Whoa, this bat is as old as El Oscuro!",
                "They'll have a heckuva year if their chest holds out!",
                "",
                "",
                "",
                "",
            }},
            {{
                "You wield the Dark Staff!",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "You picked up the Excalibat.",
                "Baseball time!",
                "Here, catch!",
                "I'm off to a field run.",
                "Whoa, this bat is as old as El Oscuro!",
                "They'll have a heckuva year if their chest holds out!",
                "",
                "",
                "",
                "",
            }},
            {{
                "You wield the Dark Staff!",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "You picked up the Excalibat.",
                "Baseball time!",
                "Here, catch!",
                "I'm off to a field run.",
                "Whoa, this bat is as old as El Oscuro!",
                "They'll have a heckuva year if their chest holds out!",
                "",
                "",
                "",
                "",
            }},
            {{
                "You wield the Dark Staff!",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "You picked up the Excalibat.",
                "Baseball time!",
                "Here, catch!",
                "I'm off to a field run.",
                "Whoa, this bat is as old as El Oscuro!",
                "They'll have a heckuva year if their chest holds out!",
                "",
                "",
                "",
                "",
            }},
            {{
                "You wield the Dark Staff!",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "You picked up the Excalibat.",
                "Baseball time!",
                "Here, catch!",
                "I'm off to a field run.",
                "Whoa, this bat is as old as El Oscuro!",
                "They'll have a heckuva year if their chest holds out!",
                "",
                "",
                "",
                "",
            }},
            {{
                "You wield the Dark Staff!",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            }},
        },
    },
    {
        {
            {{
                "Ammo Recharge Pack",
                "I'm running out of ammo! You got some?",
                "Nothing like a long-lasting battery.",
                "Eco-friendly!",
                "You know this is going straight to cells.",
                "Figured you would be running out of ammo a lot.",
                "Isn't this just a normal ammo pickup?",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Ammo Recharge Pack",
                "I'm running out of ammo! You got some?",
                "Nothing like a long-lasting battery.",
                "Eco-friendly!",
                "You know this is going straight to cells.",
                "Figured you would be running out of ammo a lot.",
                "Isn't this just a normal ammo pickup?",
                "",
                "",
                "",
            }},
        },
    },
    {{
        {{
            "Picked up Voodoo Doll.",
            "Aww, what an adorable doll. It looks just like you.",
            "I wonder what happens if I pull it like this...",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Picked up Guns Akimbo.",
            "I got two guns. That should be enough for all of ya!",
            "But wait, he can't surely have two, can he?",
            "AHAHAHAHAHA!",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Picked up Spray Can.",
            "This is how they take out wasp nests down south.",
            "Don't try this at home.",
            "Gotta do something with all this surplus deodorant.",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Training complete!",
            "Maybe now you'll actually learn how to aim.",
            "Maybe you won't blow yourself with those missiles.",
            "Because Strife is an RPG kinda game.",
            "Just a few more, and maybe that crossbow will be worth a damn.",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {
        {
            {{
                "Weapon Enhancement Chip",
                "Cat credit card!",
                "So I just plug this in, and it does stuff?",
                "I installed ram into my gun.",
                "You got the SSD of Power!",
                "Maybe now my PC can run Crysis.",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Weapon Enhancement Chip",
                "Cat credit card!",
                "So I just plug this in, and it does stuff?",
                "I installed ram into my gun.",
                "You got the SSD of Power!",
                "Maybe now my PC can run Crysis.",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Weapon Enhancement Chip",
                "Cat credit card!",
                "So I just plug this in, and it does stuff?",
                "I installed ram into my gun.",
                "You got the SSD of Power!",
                "Maybe now my PC can run Crysis.",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Weapon Enhancement Chip",
                "Cat credit card!",
                "So I just plug this in, and it does stuff?",
                "I installed ram into my gun.",
                "You got the SSD of Power!",
                "Maybe now my PC can run Crysis.",
                "",
                "",
                "",
                "",
            }},
        },
    },
    {{
        {{
            "Proximity Mines",
            "I've lost a bomb! Do you have it?",
            "I like to sit on my pancakes. *boom*",
            "Warning: Improper use of explosives will lead to a missing thigh.",
            "Time to be a dick to everyone involved.",
            "Boom time!",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Jetpack",
            "Who do you think you are? Duke Nukem?",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Weapon Supercharge!",
            "Lock and load! Lock and load your guns!",
            "Oooh, here comes the fire rate!",
            "I'm the man! I'm supercharged!",
            "Yes, a small item makes your guns shoot twice as fast without overheating, because reasons.",
            "What is this, Quake?",
            "Canon no more, but gives you more cannon!",
            "That's not how the Force works!",
            "This seems very impractical to attach to wildly inaccurate weaponry.",
            "What's better than lasers? More lasers!",
        }},
    }},
    {
        {
            {{
                "Random item!",
                "C'mon, no whammies!",
                "Get a clue!",
                "Hope I get something good this time.",
                "Nothing quite like gambling on the battlefield.",
                "I bet that mutant guy had better luck.",
                "I've got a poker face like nobody else.",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Random item!",
                "C'mon, no whammies!",
                "Get a clue!",
                "Hope I get something good this time.",
                "Nothing quite like gambling on the battlefield.",
                "I bet that mutant guy had better luck.",
                "I've got a poker face like nobody else.",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Random item!",
                "C'mon, no whammies!",
                "Get a clue!",
                "Hope I get something good this time.",
                "Nothing quite like gambling on the battlefield.",
                "I bet that mutant guy had better luck.",
                "I've got a poker face like nobody else.",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Random item!",
                "C'mon, no whammies!",
                "Get a clue!",
                "Hope I get something good this time.",
                "Nothing quite like gambling on the battlefield.",
                "I've got a poker face like nobody else.",
                "",
                "",
                "",
                "",
            }},
        },
        {
            {{
                "Random item!",
                "C'mon, no whammies!",
                "Get a clue!",
                "Hope I get something good this time.",
                "Nothing quite like gambling on the battlefield.",
                "I bet that mutant guy had better luck.",
                "I've got a poker face like nobody else.",
                "",
                "",
                "",
            }},
        },
    },
    {{
        {{
            "Picked up Blast.",
            "You're a psychic, gotta have your powers.",
            "Watch me 'splode this sucker with my mind.",
            "About three times better than MindJack.",
            "BioShock when?",
            "Gotta get my brain drugz.",
            "Will they try to pick this out of my nose with a grabby claw?",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Strength Potion",
            "You drank a bottle of Mountain Dew!",
            "Yuck, this potion tastes nasty!",
            "The liquid equivalent of anabolic steroids.",
            "Why does Grondoval drink random stuff he finds on the ground?",
            "You could probably sell this for a couple of gold pieces.",
            "How are you carrying all these potions, anyway?",
            "",
            "",
            "",
        }},
    }},
    {
        {
            {
                {
                    "Unidentified throwable bioweapon.",
                    "Do not pet the snarks.",
                    "These are not your friends. These are not pets.",
                    "Warning: Lethally annoying.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "Fragmentation grenade acquired.",
                    "Don't do drugs, kids, or the terrorists win.",
                    "A handful of shrapnel makes the medicine go down!",
                    "At least it's not tripmines.",
                    "What, were you expecting penguins with those grenades?",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
            {
                {
                    "High velocity stealth crossbow acquired.",
                    "Gordon Freeman: Dinosaur tranquilizer.",
                    "Maybe one day, this will fire hot rebar.",
                    "It's your bedtime.",
                    "Call me Ishmael, bitch!",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "7.62mm sniper rifle acquired.",
                    "It's over, Gordon. I have the AWPer hand.",
                    "FaZe Freeman.",
                    "MLG 420 quickscopes!",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
            {
                {
                    "Power-assist movement activated.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "Unidentified grapple bioweapon.",
                    "Look, Gordon! A rope! You can use it to eat the brains of others!",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
        },
        {
            {
                {
                    "Snarks",
                    "Do not pet the snarks.",
                    "These are not your friends. These are not pets.",
                    "Warning: Lethally annoying.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "Hand Grenades",
                    "Don't do drugs, kids, or the terrorists win.",
                    "What's a soldier without his grenades?",
                    "Hopefully that big orange fuck never gets a hold of these.",
                    "At least it's not tripmines.",
                    "What, were you expecting penguins with those grenades?",
                    "",
                    "",
                    "",
                    "",
                },
            },
            {
                {
                    "Crossbow",
                    "Adrian Shephard: Dinosaur tranquilizer.",
                    "Maybe one day, this will fire hot rebar.",
                    "It's your bedtime.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "M40A1 Sniper Rifle",
                    "It's over, Adrian. I have the AWPer hand.",
                    "FaZe Shephard.",
                    "MLG 420 quickscopes!",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
            {
                {
                    "Long Jump Module",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "Barnacle Grapple",
                    "Look, Adrian! A rope! You can use it to eat the brains of others!",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
        },
    },
    {{
        {{
            "Ripper Heart",
            "Who wanta some Wang?",
            "Two Wangs are better than one.",
            "There's no place like home!",
            "What is in these hearts?!",
            "Must have a lot of cholesterol to produce a whole person.",
            "",
            "",
            "",
            "",
        }},
        {{
            "Heat Seeker Card",
            "My heat seeking drivers won't install. Damn Windows updates!",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Gas Bomb",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Icon of Mann-Ra",
            "Now you play the magic lottery.",
            "This is what makes your character shine.",
            "Because your guns weren't much to write home about. What about magic?",
            "You expect me to pull a rabbit out of my hat?",
            "For my next trick, I'll saw you in half.",
            "That's it, I found the Darklight. Game's over.",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "The Ring of Ra",
            "I cast bouncy fiyabawls!",
            "Jazz hands!",
            "It's one of those light up rings in happy meals!",
            "Hope it hits something.",
            "No no! You're supposed to punch people with it!",
            "You have become a Yellow Lantern.",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Huntin' Scope Rifle!",
            "I'm goin' redneck deer huntin'!",
            "Bubba! Where'd you put the damn deer caller?",
            "Aw shucks! I forgot to oil the bolt again!",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Chicken Crossbow Ammo!!",
            "Look out! It's the crazy chicken!",
            "See? Chickens ain't no flightless birds, moran!",
            "PETA will never take me alive! AHAHAHAHAHA!",
            "Redneck anti-air defense!",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Grenade Launcher",
            "Here's a bitter pill!",
            "Is a much better use of your grenades.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Ion Ripper",
            "Isn't this the Razorjack?",
            "What goes around, comes around. Watch your head.",
            "Not the most comfortable gun grip in the world.",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Railgun",
            "Defined instagib for a generation.",
            "SNIPER DUEL!",
            "Line 'em up, knock 'em down.",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "You have acquired the Tome of Power.", // had randomized pickup message in hexen 2, use this one for differentiation for now
            "Hey, look who's back!",
            "You read one page, and it makes you feel murderous.",
            "With all these books, I should start a library.",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "You possess the Force Cube.", // had randomized pickup message in hexen 2, use this one for differentiation for now
            "Dang it, I'm shit at Rubik's Cubes.",
            "If this thing summons a Cenobite, I'll be pissed.",
            "Now you, too, can have a pet box follow you around.",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {
        {
            {
                {
                    "Picked up a sniper rifle.",
                    "Is that a sleeping bag?",
                    "Well, snipers are for campers.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
            {
                {
                    "Picked up a silenced D5K.",
                    "Now you don't have to choose between stealth and guns blazing.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "Picked up a ZMG (9mm).",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "Picked up a D5K Deutsche.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
            {
                {
                    "Picked up watch gadgets with various mines.",
                    "Oh my! Would you look at the time?",
                    "Left the base without your gadgets again, 007?",
                    "Oddjob + proxy mines = ruined friendships.",
                    "I'm not walking over there to pick up that item.",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
        },
        {
            {
                {
                    "Picked up an Armalite AR7.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
            {
                {
                    "Picked up an UZI (9mm).",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "Picked up a S&W Model 22.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                {
                    "Picked up a S&W Model 36.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
            {
                {
                    "Picked up a detonator with various mines.",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
            },
        },
    },
    {{
        {{
            "Ring of Fire, Earth, Water, or Lightning",
            "One ring to rule them all. One ring to gib them.",
            "Cheap jewelry. Disintegrates off your hand after a minute!",
            "When I said I had ice on my fingers, I wasn't thinking it was literally ice!",
            "Sleek, fashionable, makes you shoot bouncy balls or some shit...",
            "I hope I get the cherry ring pop. That's the best one!",
            "Doesn't power any crystal ball or nothing.",
            "Maybe I'll add a red ring one day. Who knows?",
            "",
            "",
        }},
    }},
    {{
        {{
            "Random Silver Tarot Card",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "You got the GES BioRifle.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "You got the Rifle.",
            "Just like a Nerf Blaster, the scope may not line up with where your crosshairs are at.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "You got the Combat Assault Rifle.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Sten",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Shotgun",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Allied Equipment Drop",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Chaingun",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Railgun",
            "A ray gun!",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Prox Launcher",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "Plasma Cannon and Proximity Bombs!",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Phoenix Cannon and Smart Mines!",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "Quad Laser Upgrade!",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
    {{
        {{
            "You found a Light Anti-Tank Weapon (LAW).",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "You found a Sniper Rifle.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
        {{
            "You found the Dragon's Tooth Sword.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        }},
    }},
};

script "SamsaraStrifeAccuracy" (int alt) //313 -- SAMSARA_STRIFEACCURACY
{
    if (!IsServer) { terminate; }

    if (GetCVar("samsara_moddedgame"))
    {
        GiveInventory("UpgradeAccuracy", 10);
        terminate;
    }

    str unique = "";
    int pclass = samsaraClassNum();

    while (!StrLen(unique) && alt >= 0)
    {
        unique = AccuracyUniques[pclass][alt];

        // hacks
        if (!StrCmp(unique, "SamsaraCorvusArtiEgg") && !isZDoom() && GetCVar("samsara_banmorphovum")) { unique = ""; }
        if (!StrCmp(unique, "HexenStrifeUnique3") && !isZDoom() && GetCVar("samsara_banmorphovum") && CheckInventory("SamsaraHexen1LoadoutUnique3") && !CheckInventory("SamsaraHasAllLoadoutEquipment")) { unique = ""; }
        if (!StrCmp(unique, "HalfLifeStrifeUnique3") && GetCVar("samsara_banjetpack")) { unique = ""; }

        alt--;
    }

    if (StrLen(unique) && IsServer)
    {
        GiveInventory(unique, 1);

        // flipped because order is handled the opposite in hexen
        if (GetCVar("samsara_currentgame") == GAME_HEXEN)
        {
            ACS_NamedExecuteAlways("SamsaraClientAccuracy", 0, alt + 1);

            if (CheckInventory("SamsaraMiscPickupDisplayExtraChoice1"))
            {
                ACS_NamedExecuteAlways("SamsaraClientMiscPickup", 0, CheckInventory("SamsaraMiscPickupDisplayExtraChoice1") - 1, CheckInventory("SamsaraMiscPickupDisplayExtraLoadout1") - 1, CheckInventory("SamsaraMiscPickupDisplayExtraDropped1"));

                SetInventory("SamsaraMiscPickupDisplayExtraChoice1", 0);
                SetInventory("SamsaraMiscPickupDisplayExtraLoadout1", 0);
                SetInventory("SamsaraMiscPickupDisplayExtraDropped1", 0);
            }
        } else {
            if (CheckInventory("SamsaraMiscPickupDisplayExtraChoice1"))
            {
                ACS_NamedExecuteAlways("SamsaraClientMiscPickup", 0, CheckInventory("SamsaraMiscPickupDisplayExtraChoice1") - 1, CheckInventory("SamsaraMiscPickupDisplayExtraLoadout1") - 1, CheckInventory("SamsaraMiscPickupDisplayExtraDropped1"));

                SetInventory("SamsaraMiscPickupDisplayExtraChoice1", 0);
                SetInventory("SamsaraMiscPickupDisplayExtraLoadout1", 0);
                SetInventory("SamsaraMiscPickupDisplayExtraDropped1", 0);
            }

            ACS_NamedExecuteAlways("SamsaraClientAccuracy", 0, alt + 1);
        }

        if (CheckInventory("SamsaraHeroMusicHalfLifeActive") && !CheckInventory("HalfLifeMusicPlayingToken")) { GiveInventory("HLMusicWeapon", 1); }
    }
}

script "SamsaraClientAccuracy" (int alt) CLIENTSIDE //314 -- SAMSARA_CLIENT_ACCURACY
{
    int pln = PlayerNumber(), cpln = ConsolePlayerNumber();
    int pclass = samsaraClassNum();
    int i, j, quoteCount = 0;
    str logMsg;
    str pickupsound = ClassUniqueSounds[pclass][SamsaraAlternativeClass][alt][SamsaraEquipmentLoadout[SLOTCOUNT + alt]];

    if (cpln == pln && GetCVar("msg") == 0)
    {
        if (GetCVar("samsara_cl_moremessages"))
        {
            for (i = 0; i < MSGCOUNT; i++)
            {
                j = AccuracyMessages[pclass][SamsaraAlternativeClass][alt][SamsaraEquipmentLoadout[SLOTCOUNT + alt]][i];

                if (!StrLen(j)) { continue; }
                QuoteStorage[quoteCount++] = j;
            }

            if (!quoteCount) { logMsg = "Oh bugger there's no messages for this unique."; }
            else { logMsg = QuoteStorage[random(0, quoteCount-1)]; }
        } else {
            logMsg = AccuracyMessages[pclass][SamsaraAlternativeClass][alt][SamsaraEquipmentLoadout[SLOTCOUNT + alt]][0];

            if (!StrLen(logMsg)) { logMsg = "Oh bugger there's no message for this unique."; }
        }

        if (GetCVar("samsara_cl_printpickup")) { Print(s:logMsg); }
        else { Log(s:msgColors[GetCVar("msg0color")], s:logMsg); }
    }

    PlaySound(0, pickupsound, CHAN_ITEM|CHAN_MAYBE_LOCAL);

    if (!CheckInventory("PickupFlashesAreDisabled"))
    {
        FadeRange(ClassFades[pclass][0], ClassFades[pclass][1], ClassFades[pclass][2], ClassFades[pclass][3],
        ClassFades[pclass][0], ClassFades[pclass][1], ClassFades[pclass][2], 0.0, itof(ClassFades[pclass][4]) / 35);
    }
}

script "SamsaraBeacon" (int noloop) //315 -- SAMSARA_BEACON
{
    int pln, classnum, monType, monTID, success = 0;
    int beaconTID = defaultTID(0);
    int x = GetActorX(0), y = GetActorY(0), z = GetActorZ(0);

    SetActivatorToTarget(0);
    
    pln = PlayerNumber();
    classnum = samsaraClassNum();

    if (pln == -1)
    {
        SetActorState(beaconTID, "WhatAmIDoingWithMyLife");
        terminate;
    }

    monType = BeaconMonsters[classnum];

    SetActivator(beaconTID);

    while (!success)
    {
        monTID = unusedTID(14000, 24000);
        success = Spawn(monType, x, y, z, monTID);
        if (success) { SetPointerExt(AAPTR_Master,0,monTID); Spawn("StrifeTeleportFog", x, y, z); }

        if (noloop)
        {
            SetResultValue(success);

            if (!success) { SetActorState(beaconTID, "FuckYouImAPickup"); }
            terminate;
        }

        Delay(1);
    }
}

script "SamsaraSpectres" (int mode, int arg1, int arg2) //316 -- SAMSARA_SPECTRES
{
    int i,j,k,l, x,y,z;
    int result;

    switch (mode)
    {
      default:
        x = GetActorX(0);
        y = GetActorY(0);
        z = GetActorZ(0);

        for (i = 0; i < 50; i++)
        {
            j = unusedTID(5000, 10000);
            Spawn("AmmoSatchel", x,y,z, j);
            k = random(0, 1.0);
            l = random(0, 1.0);

            SetActorVelocity(j, 35 * FixedMul(cos(k), cos(l)), 35 * FixedMul(sin(k), cos(l)), 35 * sin(l), 0, 0);

            if (i % 4 == 0) { Delay(1); }
        }
        break;

      case 1:
        //if ((isSinglePlayer() || isCoop()) && !isInvasion()) { SamsaraGlobal[GLOBAL_SIGILBASE + 1] = 1; } // actually called from programmer

        Floor_LowerToLowest(999, 4);

        SetActivatorToTarget(0);
        //if (!(isSinglePlayer() || isCoop()) || isInvasion()) { GiveInventory(SigilSplinters[0][1], 1); } // actually called from programmer

        GiveInventory("Communicator", 1);
        SendToCommunicator(95, 0, 0, 0);
        break;

      case 2:
        if ((isSinglePlayer() || isCoop()) && !isInvasion()) { SamsaraGlobal[GLOBAL_SIGILBASE + 2] = 1; }

        SetActivatorToTarget(0);
        if (!(isSinglePlayer() || isCoop()) || isInvasion()) { GiveInventory(SigilSplinters[1][1], 1); }

        Print(l:"TXT_KILLED_BISHOP");
        GiveInventory("Communicator", 1);
        GiveInventory("QuestItem21", 1);
        SendToCommunicator(74, 0, 0, 0);
        break;

      case 3:
        if ((isSinglePlayer() || isCoop()) && !isInvasion()) { SamsaraGlobal[GLOBAL_SIGILBASE + 3] = 1; }

        Door_Open(222, 8);
        KilledOracle = 1;
  
        SetActivatorToTarget(0);
        if (!(isSinglePlayer() || isCoop()) || isInvasion()) { GiveInventory(SigilSplinters[2][1], 1); }

        GiveInventory("Communicator", 1);
        Print(l:"TXT_KILLED_ORACLE");
        GiveInventory("QuestItem23", 1);

        if (CheckInventory("QuestItem21")) { GiveInventory("QuestItem22", 1); }

        if (CheckInventory("QuestItem24")) { SendToCommunicator(85, 0, 0, 0); }
        else { SendToCommunicator(87, 0, 0, 0); }

        Delay(35);

        KilledOracle = 0;
        break;

      case 4:
        if ((isSinglePlayer() || isCoop()) && !isInvasion()) { SamsaraGlobal[GLOBAL_SIGILBASE + 4] = 1; }

        SetActivatorToTarget(0);
        if (!(isSinglePlayer() || isCoop()) || isInvasion()) { GiveInventory(SigilSplinters[3][1], 1); }

        Print(l:"TXT_KILLED_MACIL");
        GiveInventory("Communicator", 1);
        GiveInventory("QuestItem24", 1);

        if (CheckInventory("QuestItem25")) { SendToCommunicator(106, 0, 0, 0); }
        else { SendToCommunicator(79, 0, 0, 0); }
        break;

      case 5:
        if ((isSinglePlayer() || isCoop()) && !isInvasion()) { SamsaraGlobal[GLOBAL_SIGILBASE + 5] = 1; }

        Floor_LowerToLowest(666, 4);

        SetActivatorToTarget(0);
        if (!(isSinglePlayer() || isCoop()) || isInvasion()) { GiveInventory(SigilSplinters[4][1], 1); }

        Print(l:"TXT_KILLED_LOREMASTER");
        GiveInventory("Communicator", 1);
        GiveInventory("QuestItem26", 1);

        if (GetCVar("samsara_currentgame") == GAME_HEXEN) // unnecessary unless cheating
        {
            GiveInventory("StrifeStaminaReplacement", 1);
            GiveInventory("StrifeAccuracyReplacement", 1);
        }
        else { GiveInventory("StrifeStaminaAccuracyReplacement", 1); }

        if (CheckInventory("QuestItem23") && CheckInventory("QuestItem24") && CheckInventory("QuestItem21"))
        {
            SendToCommunicator(85, 0, 0, 0);
        }
        else
        {
            SendToCommunicator(83, 0, 0, 0);
        }
        break;

      case 6:
        if (arg1 < 1 || arg1 > SIGILCOUNT)
        {
            Log(s:"\caERROR\c-: Illegal value for sigil splinter given to script ", s:"SamsaraSpectres", s:" (", d:arg1, s:")");
            break;
        }

        if ((isSinglePlayer() || isCoop()) && !isInvasion()) { SamsaraGlobal[GLOBAL_SIGILBASE + arg1] = !!arg2; }
        else { GiveInventory(SigilSplinters[arg1 - 1][1], 1); }
        break;

      case -1:
        SetActivatorToTarget(0);
        i = defaultTID(-1);

        AwakenSpectres = 1;
        SpectreTarget = i;

        Delay(35);
        AwakenSpectres = 0;
        SpectreTarget = 0;
        break;

      case -2:
        if (AwakenSpectres)
        {
            Thing_Hate(0, SpectreTarget, 0);
            SetActorState(0, "See");
        }
        break;
        
      case -3:
        result = KilledOracle;
        break;
    }

    SetResultValue(result);
}

script "SamsaraSigil" (int stuff) //317 -- SAMSARA_SIGIL
{
    switch (stuff)
    {
      case 1: // gunflash stuff
        Delay(18);
        GiveInventory("SigilInventorySequenceGunFlash1", 1);
        Delay(4);
        GiveInventory("SigilInventorySequenceGunFlash2", 1);
        Delay(6);
        GiveInventory("SigilInventorySequenceGunFlash3", 1);
        Delay(4);
        GiveInventory("SigilInventorySequenceGunFlash4", 1);
        break;

      case 2: // attack stuff
        int sigilmode = CheckInventory("StrifeSigilPiece");

        if (sigilmode > 5) { sigilmode = 5; }
        else if (sigilmode < 1) { sigilmode = 1; }

        Delay(21);
        GiveInventory(StrParam(s:"SamsaraStrifeSigilMode", d:sigilmode, s:"AttackHandler"), 1);
        break;

      case 3: // cooldown stuff
        Delay(36);
        GiveInventory("SigilInventorySequenceEnd", 1);
        break;
    }
}

script "SamsaraStrifeMinesTransmitterUniqueGiver" ENTER
{
    if (CheckInventory("SamsaraMinesTransmitterUniqueGiven") || GetCVar("samsara_currentgame") != GAME_STRIFE || GetLevelInfo(LEVELINFO_LEVELNUM) != 14) { terminate; }

    // keep a constant check on our stats to ensure they function as intended
    int orighp = GetActorProperty(0, APROP_Health);
    int origsta = GetActorProperty(0, APROP_Stamina);
    int origacc = GetActorProperty(0, APROP_Accuracy);

    while (true)
    {
        if (CheckInventory("QuestItem29"))
        {
            if (!CheckInventory("SamsaraMinesTransmitterUniqueGiven"))
            {
                if (!isDead(0)) { SetActorProperty(0, APROP_Health, orighp); }
                SetActorProperty(0, APROP_Stamina, origsta);
                SetActorProperty(0, APROP_Accuracy, origacc);

                if (GetCVar("samsara_currentgame") == GAME_HEXEN) // unnecessary unless cheating
                {
                    GiveInventory("StrifeStaminaReplacement", 1);
                    GiveInventory("StrifeAccuracyReplacement", 1);
                }
                else { GiveInventory("StrifeStaminaAccuracyReplacement", 1); }

                GiveInventory("SamsaraMinesTransmitterUniqueGiven", 1);
            }

            terminate;
        } else {
            orighp = GetActorProperty(0, APROP_Health);
            origsta = GetActorProperty(0, APROP_Stamina);
            origacc = GetActorProperty(0, APROP_Accuracy);
        }

        Delay(1);
    }
}

script "SamsaraStrifeAccuracyAmmoFiller" (int ammotype)
{
    if (GetCVar("samsara_moddedgame")) { terminate; }

    str ammoname = "Placeholder";
    int ammoamount = 0;

    int maxClip = GetCVar("samsara_max_clip");
    int maxShell = GetCVar("samsara_max_shell");
    int maxRocket = GetCVar("samsara_max_rockets");
    int maxCell = GetCVar("samsara_max_cell");
    int hasBackPack = 1 + (CheckInventory("Backpack") || CheckInventory("BagOfHolding") || CheckInventory("AmmoSatchel") || CheckInventory("Zorchpack"));

    if (maxClip < 0) { maxClip = 0; }
    if (maxShell < 0) { maxShell = 0; }
    if (maxRocket < 0) { maxRocket = 0; }
    if (maxCell < 0) { maxCell = 0; }

    int increasingClip = 0;
    int increasingShell = 0;
    int increasingRockets = 0;
    int increasingCell = 0;
    int increasingPerc = GetCVar("samsara_increasingammopercent");
    int increasingLimit = GetCVar("samsara_increasingammolimit");

    if (GetCVar("samsara_increasingammo") && increasingPerc > 0 && increasingLimit != 0)
    {
        int backPacks = max(0, CheckInventory("SamsaraBackpacksInInventory") - 1);

        if (backPacks > increasingLimit && increasingLimit >= 1) { backPacks = increasingLimit; }

        increasingClip = (maxClip * (increasingPerc * backPacks) / 100);
        increasingShell = (maxShell * (increasingPerc * backPacks) / 100);
        increasingRockets = (maxRocket * (increasingPerc * backPacks) / 100);
        increasingCell = (maxCell * (increasingPerc * backPacks) / 100);
    }

    switch (ammotype)
    {
      // Standard ammo
      case 0:
        ammoname = "Clip";
        if (CheckInventory("Hexen2Class")) { ammoamount = (((maxClip * 5) / 4) * hasBackPack) + increasingClip + CheckInventory("Hexen2BlueManaAdd"); }
        else { ammoamount = (maxClip * hasBackPack) + increasingClip; }

        if (CheckInventory("PainkillerClass") && CheckInventory("SamsaraPainkiller666AmmoActive") && ammoamount < 666) { ammoamount = 666; }
        break;

      case 1:
        ammoname = "Shell";
        ammoamount = (maxShell * hasBackPack) + increasingShell;

        if (CheckInventory("PainkillerClass") && CheckInventory("SamsaraPainkiller666AmmoActive") && ammoamount < 666) { ammoamount = 666; }
        break;

      case 2:
        ammoname = "RocketAmmo";
        ammoamount = (maxRocket * hasBackPack) + increasingRockets;

        if (CheckInventory("PainkillerClass") && CheckInventory("SamsaraPainkiller666AmmoActive") && ammoamount < 666) { ammoamount = 666; }
        break;

      case 3:
        ammoname = "Cell";
        if (CheckInventory("Hexen2Class")) { ammoamount = (((maxCell * 5) / 6) * hasBackPack) + increasingCell + CheckInventory("Hexen2GreenManaAdd"); }
        else { ammoamount = (maxCell * hasBackPack) + increasingCell; }

        if (CheckInventory("PainkillerClass") && CheckInventory("SamsaraPainkiller666AmmoActive") && ammoamount < 666) { ammoamount = 666; }
        break;

      // B.J. Blazkowicz (Castle Totenkopf SDL)
      case 4:
        ammoname = "Totenkopf_FlameThrowerFuel";
        ammoamount = (maxCell * hasBackPack) / 3;
        break;

      // Duke Nukem (Original/Life's A Beach)
      case 5:
        ammoname = "ShrinkerAmmo";
        ammoamount = (maxCell * hasBackPack) / 10;
        break;

      case 6:
        ammoname = "ExpanderAmmo";
        ammoamount = (maxCell * hasBackPack) / 3;
        break;

      // H.U.N.T. Team Members
      case 7:
        ammoname = "BMissiles";
        ammoamount = (maxCell + increasingCell) / 30;
        break;

      case 8:
        ammoname = "DSEnergy";
        ammoamount = (maxCell + increasingCell) / 30;
        break;

      // Caleb
      case 9:
        ammoname = "SprayCanAmmo";
        ammoamount = ((maxCell * hasBackPack) / 48) * 48;
        break;

      // B.J. Blazkowicz (Return To Castle Wolfenstein)
      case 10:
        ammoname = "RTCW_AlliedAmmo1";
        ammoamount = (maxClip * hasBackPack) / 2;
        break;

      case 11:
        ammoname = "RTCW_AlliedAmmo2";
        ammoamount = (maxShell * hasBackPack) / 2;
        break;

      case 12:
        ammoname = "RTCW_AlliedAmmo3";
        ammoamount = (maxRocket * hasBackPack) / 2;
        break;

      // Sarge
      case 13:
        ammoname = "Q3ChaingunAmmo";
        ammoamount = (maxClip * hasBackPack / 2) * 3;
        break;

      case 14:
        ammoname = "Q3GrenadeLauncherAmmo";
        ammoamount = (maxRocket * hasBackPack / 2) * 3;
        break;

      // Default
      default:
        terminate;
    }

    if (GetCVar("samsara_noammocap")) { SetInventory(ammoname, CheckInventory(ammoname) + ammoamount); }
    else { SetInventory(ammoname, GetAmmoCapacity(ammoname)); }
}

script "SamsaraStrifeAcolyteBlueDeathChecker" (void) // Haaaaack.
{
    if (!isZDoom() && !ThingCountName("AcolyteBlue2", 0))
    {
        for (int i = 0; i < PLAYERMAX; i++)
        {
            if (!PlayerInGame(i)) { continue; }

            SetPlayerActivator(i);

            if (!isDead(0) && !CheckInventory("QuestItem7"))
            {
                bool hadcommunicator = CheckInventory("Communicator"); // bypass item requirement if you're cheating

                GiveInventory("QuestItem7", 1);

                if (!hadcommunicator) { GiveInventory("Communicator", 1); }
                SendToCommunicator(14, 0, 14, 0);
                if (!hadcommunicator) { TakeInventory("Communicator", 0x7FFFFFFF); }
            }
        }
    }
}
