#define SAMSARA_CHANGELIST         23

#define SAMSARA_ENTER               611
#define SAMSARA_RETURN              613
#define SAMSARA_RESPAWN             618
#define SAMSARA_DEATH               619
#define SAMSARA_OPEN                623
#define SAMSARA_SPAWN               624
#define SAMSARA_DISCONNECT          617
#define SAMSARA_WOLFMOVE            673
#define SAMSARA_SCHEDULED           674
#define SAMSARA_PDWTAK              675
#define SAMSARA_GETSETTINGS         676
#define SAMSARA_SPACEFLIGHT         681

#define SAMSARA_CONFIRMCLASS        206
#define SAMSARA_DECORATE            215
#define SAMSARA_GIVEWEAPON          229
#define SAMSARA_GIVEUNIQUE          231
#define SAMSARA_CLIENT_WEAPONPICKUP 616
#define SAMSARA_CLIENT_UNIQUEPICKUP 633
#define SAMSARA_MARATHON            609
#define SAMSARA_QUAKE               606
#define SAMSARA_RESONATE            608
#define SAMSARA_SYNTHFIRE           607
#define SAMSARA_MEGAHEALTH          259
#define SAMSARA_QPOWERS             636
#define SAMSARA_BITTERMAN      		806
#define SAMSARA_STRIFESIGIL			667
#define SAMSARA_DOOM64              666
#define SAMSARA_REBELMOON			665
#define SAMSARA_WT_AUTOHEALER		708 //+Added
#define SAMSARA_WT_CLIP				709 //+Added
#define SAMSARA_WANGHEAD            712
//#define HL_RELOADER_SCRIPT 			592
#define HL_GAUSS_SCRIPT				622

#define SAMSARA_PUKE                226
#define SAMSARA_PUKE_CLIENT         227
#define SAMSARA_OPEN_CLIENT         548
#define SAMSARA_ENTER_CLIENT        521
#define SAMSARA_DISCONNECT_CLIENT   522
#define SAMSARA_CLIENT_CLASS        228
#define SAMSARA_RECOIL              312
#define SAMSARA_CLIENT_DECORATE     212

#define SAMSARA_STRIFEACCURACY      313
#define SAMSARA_CLIENT_ACCURACY     314
#define SAMSARA_BEACON              315
#define SAMSARA_SPECTRES            316
#define SAMSARA_SIGIL               317

#define SAMSARA_CL_VERSION          20000

#define MAXMODES          	5
#define CLASSCOUNT          34
#define UNIQUECOUNT         3
#define SLOTCOUNT           13
#define MISCPICKUPCOUNT     49
#define ORIGINALCOUNT       10

#define LMSMODES            6
#define ARMORMODES          6

#define CLASS_DOOM      0
#define CLASS_CHEX      1
#define CLASS_HERETIC   2
#define CLASS_WOLFEN    3
#define CLASS_HEXEN     4
#define CLASS_DUKE      5
#define CLASS_MARATHON  6
#define CLASS_QUAKE     7
#define CLASS_ROTT      8 // Added this.
#define CLASS_BLAKE		9 // Added this.
#define CLASS_CALEB     10 // added this.
#define CLASS_STRIFE    11 // added this.
//#define CLASS_DOOM64    12 // bye bye bye!
#define CLASS_ERAD      12 // added this.
#define CLASS_C7   		13 // Added this. 
#define CLASS_RMR   	14 // Added this. 
#define CLASS_KATARN    15
#define CLASS_POGREED	16	//+Added
#define CLASS_DISRUPTOR	17	//+Added
#define CLASS_WITCHAVEN	18	//+Added
#define CLASS_HALFLIFE	19	//+Added
#define CLASS_SW		20
#define CLASS_CM		21
#define CLASS_JON		22
#define CLASS_RR		23
#define CLASS_BITTERMAN	24
#define CLASS_DEMONESS	25
#define CLASS_BOND		26
#define CLASS_CATACOMB	27
#define CLASS_PAINKILLER	28
#define CLASS_UNREAL 29
#define CLASS_RTCW 30
#define CLASS_QUAKE3 31
#define CLASS_DESCENT 32
#define CLASS_DEUSEX 33

#define GAME_DOOM 1
#define GAME_CHEX 2
#define GAME_HERETIC 4
#define GAME_HEXEN 8
#define GAME_STRIFE 16
#define GAME_HACX 32
#define GAME_HARMONY 64
#define GAME_ROTWB 128
#define GAME_SQUARE 256
#define GAME_REKKR 512

#define SPEED_FORWARD       15
#define SPEED_SIDE          13

#define UNLOADCOUNT 128
#define DEATHREMOVECOUNT 10

#define P_COUNT 2
#define P_QUAD  0
#define P_REGEN 1

#define QUAD_THRESHOLD      2100   // one minute

#define PY640   320.0
#define PY320   (PY640/2)

#define POFF640 40.0
#define POFF320 20.0

#define REGEN_CENTER_X      0.953125    // 610 / 640
#define REGEN_CENTER_Y      (PY640 / 480)
#define REGEN_OFFSET        0.083333    // 40 / 480

#define TIP_SCROLLRATE      8

#define BLOODYHELL_SONIC		-4
#define BLOODYHELL_FOODFIGHT	-3
#define BLOODYHELL_COMIC		-2
#define BLOODYHELL_HAPPYFUN		-1
#define BLOODYHELL_VANILLA		0
#define BLOODYHELL_NASHGORE		1
#define BLOODYHELL_NASHGORE2D	2
#define BLOODYHELL_CHUNKY		3
#define BLOODYHELL_CHUNKY2D		4
#define BLOODYHELL_NIGHTMARE	5
#define BLOODYHELL_NIGHTMARE2D	6
#define BLOODYHELL_BOLOGNESE	7
#define BLOODYHELL_KETCHUP		8
#define BLOODYHELL_TREMOR		9
#define BLOODYHELL_DBT			10
#define BLOODYHELL_SMOOTH		11

#define GLOBAL_DONEBITCHING     0
#define GLOBAL_SIGILBASE        1

int currentGame = 1;

int HELPSTR = 
"Welcome to the Wheel of Samsara! There are a few optional RCon commands you may want to consider.\n\
samsara_banjetpack 0/1: Toggles whether certain classes are allowed to use items that could potentially skip levels.\n\
samsara_banwolfmove 0/1: Toggles whether Wolfenstein movement is allowed or not.\n\
samsara_nocustomgravity 0/1: Toggles whether certain classes are affected by their own gravity or Doom's gravity.\n\
samsara_weaponbalance [0-2]: Toggles if the older classes can deal extra damage. Useful for ReMixer, but should be toggled off if using only Reincarnation.\n\
samsara_descentflight [0-2]: Toggles the unique movement for Pyro-GX.\n\
samsara_armormode [0-4]: Toggles the type of armor that spawns in-game.\n\
samsara_nohealthcap 0/1: Toggles whether classes have capped health like in Doom, or if the health cap is removed.\n\
samsara_noarmorcap 0/1: Toggles whether classes have capped armor like in Doom, or if the armor cap is removed.\n\
samsara_jumpmod [-25-200]: Increases or decreases jump height for classes. The range for the setting is -25 to 200.\n\
samsara_speedmod [-6-10]: Increases or decreases running speed for classes. The range for the setting is -6 to 10.\n\
samsara_permault 0/1: Toggles whether the Slot VII stays or vanishes on pickup.\n\
samsara_lmsrules 0/1: For players who want Rocket Arena-style showdowns or just to spawn with all weapons.\n\
samsara_lmshealth [0-400]: Affects how much extra health people have on LMS spawn/respawn.\n\
samsara_lmsarmor [0-500]: Affects how much armor people have on LMS spawn/respawn.\n\
samsara_lmsarmortier [0-4]: Determines the tier of the armor given on LMS spawn/respawn.\n\
samsara_lmsuniques 0/1: Toggles whether players get their Uniques in LMS.\n\
samsara_lms[slot] 0/1: Toggles whether players get their specified Slots in LMS. lmschainsaw for Slot I, lmsshotgun for Slot II, etc.\n\
samsara_lmsbackpack 0/1: Toggles whether players get an Ammo Expansion Pack in LMS, along with any backpack weapons if they have them.\n\
samsara_uniquestart [0-4]: Toggles whether players get their Uniques on enter or spawn.\n\
samsara_[slot]start [0-2]: Toggles whether players get their specified Slots on enter or spawn. chainsawstart for Slot I, shotgunstart for Slot II, etc. Look at MENUDEF for a complete list.\n\
samsara_backpackstart 0/1: Toggles whether players get an Ammo Expansion Pack on spawn, along with any backpack weapons if they have them.\n\
samsara_pdwtak_damage [0-8192]: Adjusts the amount of damage players' party mode death explosions deal on death.\n\
samsara_pdwtak_distance [0-2048]: Adjusts the amount of map units players' party mode death explosions can cover.\n\
samsara_pdwtak_fulldamagedistance [0-2048]: Adjusts the amount of map units players' party mode death explosions deal full damage at.\n\
samsara_permaweaponlevel2 0/1: Toggles a party mode that powers up weapons if a class is able to access them.\n\
samsara_randomcharacters [0-100]: Adjusts the percentage chance of miscellaneous characters spawning randomly on the map.\n\
samsara_misccharacterspawnmode 0/1: Toggles if the miscellanous character spawns are class-based or dependent on toggled sets.\n\
samsara_ban[class] 0/1: Forbids players from playing certain classes. bandoomguy for Doomguy, banchex for Chex Warrior, etc. Look at MENUDEF for a complete list.\n\
samsara_[class]damage [-10-30]: Adjusts the character's damage multiplier. Look at MENUDEF for a complete list.\n\
samsara_[class]defense [-10-20]: Adjusts the character's defense multiplier. Look at MENUDEF for a complete list.\n\
For more serverside console variables and detailed information about them, look at the Compendium.";

int HELPSTR_CL = 
"Likewise, there are several clientside console variables, including:\n\
samsara_cl_printpickup 0/1: Toggles whether weapon pickup messages are printed or logged. 1 = Print, 0 = Log.\n\
samsara_cl_weaponhud 0/1: Controls whether the weapon bar at the top of your screen appears. Useful for multiplayer.\n\
samsara_cl_moremessages 0/1: Toggles extra weapon pickup messages, usually with a comedic slant for the extra messages.\n\
samsara_cl_norecoil 0/1: Toggles the vertical recoil some weapons exhibit, such as Ranger's weapons.\n\
samsara_cl_smoothanims 0/1: Toggles the smooth weapon animations for certain weapons.\n\
samsara_cl_wolfmove 0/1: Toggles classic Wolfenstein movement on B.J. Blazkowicz, Blake Stone, Space Seal, and Petton Everhail.\n\
samsara_cl_expparticles [0-100000]: Controls how many particles Ranger's explosions emit. 0 is default, -1 to disable.\n\
samsara_cl_heromusic [0/3]: Toggles if the selected class plays the soundtrack from their game, a selected soundtrack, or the QC:DE soundtrack. This setting requires the Samsara or QC:DE OSTs to be loaded.\n\
samsara_cl_bloodyhell [-3/9]: Toggles between multiple blood settings.\n\
For more clientside console variables and detailed information about them, look at the Compendium.";

str ClassNames[CLASSCOUNT][3] =
{
    {"DoomguyPlayer",     "DoomguyClass",      "DoomClassMode"},
    {"ChexWarrior",       "ChexClass",         ""},
    {"CorvusPlayer",      "CorvusClass",       ""},
    {"WolfenPlayer",      "WolfenClass",       "WolfenClassMode"},
    {"HexenPlayer",       "HexenClass",        "HexenClassMode"},
    {"DukePlayer",        "DukeClass",         "DukeClassMode"},
    {"MarathonPlayer",    "MarathonClass",     ""},
    {"QuakePlayer",       "QuakeClass",        ""},
    {"IPFreeley",         "RottClass",         "RottMode"},
    {"BlakeStone",        "BlakeClass",        ""},
    {"Caleb",             "CalebClass",        ""},
    {"StrifeguyPlayer",   "StrifeClass",       ""},
    {"Eleena",            "EradClass",         "EradMode"},
    {"Corridor7Player",   "C7Class",           ""},
    {"RebelMoonCommando", "RMRClass",          ""},
    {"KatarnPlayer",      "KatarnClass",       ""},
    {"POGreedPlayer",     "POGreedClass",      "IpogMode"},
    {"DisruptorPlayer",   "DisruptorClass",    ""},
    {"GrondovalPlayer",   "WitchavenClass",    ""},
    {"HalfLifePlayer",    "HalfLifeClass",     "HalfLifeOpposingForce"},
    {"LoWangPlayer",      "SWClass",           ""},
    {"CMPlayer",          "CMClass",           ""},
    {"PSPlayer",          "JonClass",          ""},
    {"Leonard",           "RRClass",           ""},
    {"Bitterman",         "BittermanClass",    ""},
    {"Demoness",          "Hexen2Class",       ""},
    {"JamesBond",         "BondClass",         "Goldeneye_PlayerAltClassToken"},
    {"PettonEverhail",    "CatacombClass",     ""},
    {"DanielGarner",      "PainkillerClass",   ""},
    {"UnrealPlayer",      "UnrealClass",       ""},
    {"RTCW_Blazkowicz",   "RTCWClass",         ""},
    {"Q3Sarge",           "Q3Class",           ""},
    {"DescentPyroGX",     "DescentClass",      ""},
    {"JCDenton",          "DeusExClass",       ""},
};

int PickupStates[CLASSCOUNT][24] = 
{
    {"Doomguy", "DoomFull",     "DoomEmpty",        "DoomSpecial",      "DoomPunchdrunk",      "DoomPDFull",       "DoomPDEmpty",      "DoomPDSpecial",		"Doom64",		"Doom64Full",		"Doom64Empty",		"Doom64Special", "DoomguyStr", "DoomStrFull", "DoomStrEmpty", "DoomStrSpecial"},
    {"Chexguy", "ChexFull",     "ChexEmpty",        "ChexSpecial",      "ChexPunchdrunk",      "ChexPDFull",       "ChexPDEmpty",      "ChexPDSpecial",		"",		"",		"",		""},
    {"Heretic", "HereticFull",  "HereticEmpty",     "HereticSpecial",   "HereticPunchdrunk",   "HereticPDFull",    "HereticPDEmpty",   "HereticPDSpecial",		"",		"",		"",		""},
    {"Wolfguy", "WolfFull",     "WolfEmpty",        "WolfSpecial",      "WolfPunchdrunk",      "WolfPDFull",       "WolfPDEmpty",      "WolfPDSpecial",		"LostWolfGuy",		"LostWolfFull",		"LostWolfEmpty", "LostWolfSpecial", "Totenkopf", "TotenkopfFull", "TotenkopfEmpty",  "TotenkopfSpecial"},
    {"Hexen",   "HexenFull",    "HexenEmpty",       "HexenSpecial",     "HexenPunchdrunk",     "HexenPDFull",      "HexenPDEmpty",     "HexenPDSpecial",	"HexenClassic",	"HexenClassicFull",	"HexenClassicEmpty", "HexenClassicSpecial",		"HexenMage",		"HexenMageFull",		"HexenMageEmpty",		"HexenMageSpecial", "HexenFighter",	"HexenFighterFull",	"HexenFighterEmpty", "HexenFighterSpecial" },
    {"Dukeguy", "DukeFull",     "DukeEmpty",        "DukeSpecial",      "DukePunchdrunk",      "DukePDFull",       "DukePDEmpty",      "DukePDSpecial",		"BeachDukeguy",		"BeachDukeFull",		"BeachDukeEmpty",		"BeachDukeSpecial", 	"Duke64guy", "Duke64Full",     "Duke64Empty",        "Duke64Special",},
    {"Marathon","MarathonFull", "MarathonEmpty",    "MarathonSpecial",  "MarathonPunchdrunk",  "MarathonPDFull",   "MarathonPDEmpty",  "MarathonPDSpecial",		"",		"",		"",		""},
    {"Quake",   "QuakeFull",    "QuakeEmpty",       "QuakeSpecial",     "QuakePunchdrunk",     "QuakePDFull",      "QuakePDEmpty",     "QuakePDSpecial",		"",		"",		"",		""},   
	{"Rott",    "RottFull",     "RottEmpty",        "RottSpecial",      "",						"",					"", 				"RottSpecial2",			"Rott",		"RottFull",		"RottEmpty",		"RottSpecial",		"Rott",    "RottFull",     "RottEmpty",        "RottSpecial",	"Rott",    "RottFull",     "RottEmpty",        "RottSpecial",	"Rott",    "RottFull",     "RottEmpty",        "RottSpecial" },   // Added this
	{"Blake",   "BlakeFull",	"BlakeEmpty",		"BlakeSpecial",		"","","", "BlakeSpecial2",		"AOG",		"AOGFull",		"AOGEmpty",		"AOGSpecial"}, // Added this
	{"Caleb",   "CalebFull",    "CalebEmpty",       "CalebSpecial",     "","","", "CalebSpecial2",		"",		"",		"",		""}, // Added this
	{"Strifeguy",  "StrifeFull",   "StrifeEmpty",      "StrifeSpecial",    "StrifePunchdrunk",    "StrifePDFull",     "StrifePDEmpty",    "StrifePDSpecial",		"",		"",		"",		""},	
//    {"Doom64",  "Doom64Full",   "Doom64Empty",      "Doom64Special",    "Doom64Punchdrunk",    "Doom64PDFull",     "Doom64PDEmpty",    "Doom64PDSpecial",		"",		"",		"",		""},
    {"Erad",   "EradFull",    "EradEmpty",       "EradSpecial",     "EradPunchdrunk",     "EradPDFull",      "EradPDEmpty",     "EradPDSpecial",	"EradKamchak",	"EradKamchakFull",	"EradKamchakEmpty", "EradKamchakSpecial",		"EradDan",		"EradDanFull",		"EradDanEmpty",		"EradDanSpecial", "EradMarine",	"EradMarineFull",	"EradMarineEmpty", "EradMarineSpecial" },
    {"C7",      "C7Full",       "C7Empty",          "C7Special",        "C7Punchdrunk",        "C7PDFull",         "C7PDEmpty",        "C7PDSpecial",		"",		"",		"",		""},
    {"RMR",      "RMRFull",       "RMREmpty",          "RMRSpecial",        "",        "",         "",        ""},	
    {"Katarn",  "KatarnFull",   "KatarnEmpty",      "KatarnSpecial",    "KatarnPunchdrunk",    "KatarnPDFull",     "KatarnPDEmpty",    "KatarnPDSpecial",		"",		"",		"",		""},	
	{"POGreed",		"POGreedFull",	"POGreedEmpty",		"POGreedSpecial",	"POGreedPunchdrunk",	"POGreedPDFull",	"POGreedPDEmpty",	"POGreedPDSpecial",		"POGreed",		"POGreedFull",		"POGreedEmpty",		"POGreedSpecial",		"POGreed",		"POGreedFull",		"POGreedEmpty",		"POGreedSpecial",		"POGreed",		"POGreedFull",		"POGreedEmpty",		"POGreedSpecial",		"POGreed",		"POGreedFull",		"POGreedEmpty",		"POGreedSpecial"},
    {"Disruptor",      "DisruptorFull",       "DisruptorEmpty",          "DisruptorSpecial",        "",        "",         "",        "",		"",		"",		"",		""},	
	{"Witchaven",	"WitchavenFull","WitchavenEmpty",	"WitchavenSpecial",	"WitchavenPunchdrunk",	"WitchavenPDFull",	"WitchavenPDEmpty",	"WitchavenPDSpecial",		"",		"",		"",		""},
	{"HalfLife",	"HalfLifeFull",	"HalfLifeEmpty",	"HalfLifeSpecial",	"HalfLifePunchDrunk",	"HalfLifePDFull",	"HalfLifePDEmpty",	"HalfLifePDSpecial",		"HalfLife",		"HalfLifeFull",		"HalfLifeEmpty",		"HalfLifeSpecial"},
	{"SW",	"SWFull",	"SWEmpty",	"SWSpecial",	"",	"",	"",	"",		"",		"",		"",		""},	
	{"CM",	"CMFull",	"CMEmpty",	"CMSpecial",	"",	"",	"",	"",		"",		"",		"",		""},	
	{"Jon",	"JonFull",	"JonEmpty",	"JonSpecial",	"",	"",	"",	"",		"",		"",		"",		""},	
	{"RR",	"RRFull",	"RREmpty",	"RRSpecial",	"",	"",	"",	"",		"",		"",		"",		""},	
	{"Bitterman",    "BittermanFull",     "BittermanEmpty",        "BittermanSpecial",      "BittermanPunchdrunk",      "BittermanPDFull",       "BittermanPDEmpty",      "BittermanPDSpecial",		"",		"",		"",		""}, 
	{"Demoness",    "DemonessFull",     "DemonessEmpty",        "DemonessSpecial",      "DemonessPunchdrunk",      "DemonessPDFull",       "DemonessPDEmpty",      "DemonessPDSpecial",		"",		"",		"",		""},
	{"Bond",    	"BondFull",     	"BondEmpty",        	"BondSpecial",      	"BondPunchdrunk",      	   "BondPDFull",       	   "BondPDEmpty",          "BondPDSpecial",		    "Goldfinger",		"GoldfingerFull",		"GoldfingerEmpty",		"GoldfingerSpecial"},
	{"Catacomb",    "CatacombFull",     	"CatacombEmpty",        	"CatacombSpecial",      	"CatacombPunchdrunk",      	   "CatacombPDFull",       	   "CatacombPDEmpty",          "CatacombPDSpecial",		    "",		"",		"",		""},
	{"Painkiller",    "PainkillerFull",     	"PainkillerEmpty",        	"PainkillerSpecial",      	"PainkillerPunchdrunk",      	   "PainkillerPDFull",       	   "PainkillerPDEmpty",          "PainkillerPDSpecial",		    "",		"",		"",		""},
	{"Unreal",    "UnrealFull",     	"UnrealEmpty",        	"UnrealSpecial",      	"UnrealPunchdrunk",      	   "UnrealPDFull",       	   "UnrealPDEmpty",          "UnrealPDSpecial",		    "",		"",		"",		""},	
	{"RTCW",    "RTCWFull",     	"RTCWEmpty",        	"RTCWSpecial",      	"RTCWPunchdrunk",      	   "RTCWPDFull",       	   "RTCWPDEmpty",          "RTCWPDSpecial",		    "",		"",		"",		""},	
	{"Sarge",    "SargeFull",     	"SargeEmpty",        	"SargeSpecial",      	"SargePunchdrunk",      	   "SargePDFull",       	   "SargePDEmpty",          "SargePDSpecial",		    "",		"",		"",		""},
	{"Descent",    "DescentFull",     	"DescentEmpty",        	"DescentSpecial",      	"DescentPunchdrunk",      	   "DescentPDFull",       	   "DescentPDEmpty",          "DescentPDSpecial",		    "",		"",		"",		""},
	{"DeusEx", 	  "DeusExFull",		"DeusExEmpty",			"DeusExSpecial", 		"DeusExPunchdrunk",				"DeusExPDFull",				"DeusExPDEmpty",			"DeusExPDSpecial",			"",		"",		"",		""},
};

int ItoSArray[13] = {1, 3, 4, 5, 6, 7, 8, 0, 2, 9, 10, 11, 12};

int ClassFades[CLASSCOUNT][5] =
{
    {255, 255, 0,   0.1, 5},
    {255, 255, 0,   0.1, 5},
    {255, 255, 0,   0.1, 5},
    {255, 255, 0,   0.1, 5},
    {255, 255, 0,   0.1, 5},
    {255, 255, 0,   0.1, 5},
    {0,   255, 0,   0.4, 8},
    {255, 255, 0,   0.1, 5},
	{255, 255, 0,   0.1, 5},
    {255, 255, 0,   0.1, 5},
	{255, 255, 0,   0.1, 5},
//	{255, 255, 0,   0.1, 5},	
	{255, 255, 0,   0.1, 5},	
	{255, 255, 0,   0.1, 5},
    {255, 255, 0,   0.1, 5},	
    {255, 255, 0,   0.1, 5},		
    {255, 255, 0,   0.1, 5},	
	{255, 255, 0,	0.1, 5},	
	{255, 255, 0,	0.1, 5},		
	{0,	  0,   0,	0,	 0}, //+Added (Witchaven pickups caused no flash)
	{0,   0,   0,   0,   0}, //+Added	
	{255, 255, 0,	0.1, 5},
	{255, 255, 0,	0.1, 5},	
	{255, 255, 0,	0.1, 5},	
	{255, 255, 0,	0.1, 5},	
	{255, 255, 0,	0.1, 5},	
	{255, 255, 0,	0.1, 5},	
	{0,   0,   0,   0,   0},
	{255, 255, 0,	0.1, 5},	
	{255, 255, 0,	0.1, 5},	
	{255, 255, 0,	0.1, 5},
	{0,   0,   0,   0,   0},
	{255, 255, 0,	0.1, 5},
	{255, 255, 0,	0.1, 5},
	{0,   0,   0,   0,   0},
};

int SlotItems[SLOTCOUNT] = 
{
    "",
    "GotWeapon0",
    "",
    "GotWeapon2",
    "GotWeapon3",
    "GotWeapon4",
    "GotWeapon5",
    "GotWeapon6",
    "GotWeapon7",
    "",
};

/*str LMSItems[CLASSCOUNT] =
{
    "",
    "",
    "PortGhostly",
    "WolfenAmmoCrate",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};*/

int UnloadRemove[UNLOADCOUNT] =
{
    "SamsaraDiscOfRepulsionCooldown", "SamsaraDarkServantCooldown", "HolodukeCooldown",
    "RainTracker", "DukeTauntCooldown", "DukeFlying", "DukeJPMotor", "DukeVision",
    "DukeSteroidsActive", "DukeReady", "DukeWaiting", "SamsaraSynthFireActive",
    "SamsaraSynthFireReload", "SamsaraSynthFireLeft", "SamsaraSynthFireLeftPress",
    "SamsaraSynthFireRight", "SamsaraSynthFireRightPress", "LeftReload", "RightReload",
    "QuakeQuadTimer", "SamsaraQuadDamageCooldownDisplay", "QuakeRegenTimer", "QuakeInvisTimer",
    "QuakePentTimer", "QuakeBioTimer", "ChickenKillCount", "GibfistSide", "God Hand",
    "SamsaraBStoneAutoChargePistolCooldown", "DBSHOT", "DBSHOT1", "DB1", "DB2", "DB3", "DB4",
    "DB5", "DB6", "DB7", "DB8", "DB9", "DB10", "DB11", "DB12", "DB13", "DB14", "DB15", "DB16",
    "DB17", "DB18", "DB19", "StopFromPickingShit", "EleenaTauntCooldown", "LeonardTauntCooldown",
    "CalebTauntCooldown", "LoWangTauntCooldown", "SWLoWangBloody", "JonTauntCooldown",
    "StopFromPickingTurrets_", "StrifeBeaconCooldown", "SamsaraBloodGunsAkimboCooldown",
    "DisruptorPSICooldown", "Catacomb_HourglassCooldown", "FlechetteCooldown",
    "Flechette2Cooldown", "Flechette3Cooldown", "IPOGGrenadeCooldown",
    "SamsaraHeroMusicHalfLifeActive", "SamsaraHeroMusicPainkillerActive",
    "SamsaraHeroMusicDeusExActive", "HalfLifeMusicPlayingToken", "RTCW_VenomHeat", "RTCW_MG42Heat",
    "RTCW_BrowningHeat", "RTCW_StenHeat", "SamsaraHalfLifeLaserSightReady", "HLHornetGunRegenLock",
    "HLShockRoachRegenLock", "HLOPBarnacleTetherActive", "TimeBombCount", "TimeBombPause",
    "CorvusRemoteActive", "CorvusRemoteDetonate", "SamsaraTrickyBombElfArmTimer",
    "SamsaraHereticProxyBombCount", "Unreal_TargetLocked", "Unreal_EightballLockTimer",
    "SamsaraUnrealEightballLockSoundRepeat", "SamsaraUnrealEightballLockDisabled",
    "SamsaraUnrealRedeemerMainRocketControlled", "SamsaraUnrealCARifleSecondaryCooldown",
    "DeusEx_GEPGunLockTimer", "SamsaraDeusExGEPGunLockDisabled",
    "SamsaraHalfLifeSAWReloadCooldown", "SamsaraHalfLifeSniperReloadCooldown",
    "Goldeneye_UsingTank", "RRHasBike", "CalebVision", "freeman_fistselected",
    "freeman_slot1selected", "freeman_slot2selected", "freeman_slot3selected",
    "freeman_slot4selected", "freeman_slot5selected", "freeman_slot6selected",
    "freeman_slot7selected", "freeman_uniqueselected", "freeman_unique2selected",
    "freeman_unique3selected", "Totenkopf_MauserLevelLimiter", "Totenkopf_MP40LevelLimiter",
    "MarathonShotgunLevelLimiter", "SWUziLevelLimiter", "Goldeneye_KnifeLevelLimiter",
    "Goldeneye_KF7SovietLevelLimiter", "Goldeneye_AutoShotgunLevelLimiter",
    "Goldeneye_AR33LevelLimiter", "Goldeneye_PhantomLevelLimiter",
    "Goldeneye_RocketLauncherLevelLimiter", "Goldeneye_GrenadeLauncherLevelLimiter",
    "Goldeneye_RCP90LevelLimiter", "Goldeneye_CougarLevelLimiter", "Goldeneye_LaserLevelLimiter",
    "Goldeneye_GoldenGunLevelLimiter", "Goldeneye_SniperLevelLimiter", "Goldeneye_D5KLevelLimiter",
    "EradDartGunCounter", "ROTTNetNoWeapon", "SamsaraPainkiller666AmmoActive"
};

int DeathRemove[DEATHREMOVECOUNT] =
{
    "DukeVision", "DukeFlying", "DukeSteroidsActive", "DukeKaboom", "AmAlreadyChoked", "Chokeme",
    "MagicCircleCounter", "MagicCircleSpawner", "CalebVision", "ROTTNetNoWeapon"
};

int PowerOutVols[5] = {96, 104, 112, 120, 127};

#define RESCOUNT 2
int ResonantItems[RESCOUNT] =
{
    "UnknownResonator1",
    "UnknownResonator2",
};

int ResonantAmounts[RESCOUNT][2] =
{
    {0, -1},
    {0, -1},
};

str PeopleDieStuff[CLASSCOUNT][MAXMODES][4] = 
{
    {
        {"DoomguysDieParticle",    "DoomguysDiePulse",    "DoomguyDiesWhenHeIsKilled",      "InvPeopleDie"},
        {"Doomguys64DieParticle",  "Doomguys64DiePulse",  "Doomguy64DiesWhenHeIsKilled",    "InvPeopleDie"},
        {"DoomguysStrDieParticle", "DoomguysStrDiePulse", "DoomguyStrDiesWhenHeIsKilled",   "InvPeopleDie"},
    },
    {{"ChexguysDieParticle",       "ChexguysDiePulse",    "ChexguyDiesWhenHeIsKilled",      "InvPeopleZorch"}},
    {{"CorvusDiesParticle",        "CorvusDiesPulse",     "CorvusDiesWhenHeIsKilled",       "InvPeopleDie"}},
    {
        {"BlazkoDiesParticle",     "BlazkoDiesPulse",     "BlazkoDiesWhenHeIsKilled",       "InvPeopleDie"},
        {"BlazkoDiesParticle",     "BlazkoDiesPulse",     "BlazkoDiesWhenHeIsKilled",       "InvPeopleDie"},
        {"BlazkoCTKDiesParticle",  "BlazkoCTKDiesPulse",  "BlazkoCTKDiesWhenHeIsKilled",    "InvPeopleDie"},
    },
    {
        {"PariasDiesParticle",     "PariasDiesPulse",     "PariasDiesWhenHeIsKilled",       "InvPeopleDie"},
        {"PariasDiesParticle",     "PariasDiesPulse",     "PariasDiesWhenHeIsKilled",       "InvPeopleDie"},
        {"PariasDiesParticle",     "PariasDiesPulse",     "PariasDiesWhenHeIsKilled",       "InvPeopleDie"},
        {"PariasDiesParticle",     "PariasDiesPulse",     "PariasDiesWhenHeIsKilled",       "InvPeopleDie"},
    },
    {
        {"DukeguysDieParticle",    "DukeguysDiePulse",    "DukeDiesWhenHeIsKilled",         "InvPeopleDie"},
        {"DukeguysDieParticle",    "DukeguysDiePulse",    "DukeDiesWhenHeIsKilled",         "InvPeopleDie"},
        {"Dukeguys64DieParticle",  "Dukeguys64DiePulse",  "Duke64DiesWhenHeIsKilled",       "InvPeopleDie"},
    },
    {{"VidBoisDieParticle",        "VidBoisDiePulse",     "ManathorDiesWhenHeIsKilled",     "InvPeopleDie"}},
    {{"RangersDieParticle",        "RangersDiePulse",     "RangerDiesWhenHeIsKilled",       "InvPeopleDie"}},
    {
        {"FreeleyDieParticle",     "FreeleyDiePulse",     "FreeleyDiesWhenHeIsKilled",      "InvPeopleDie"},
        {"FreeleyDieParticle",     "FreeleyDiePulse",     "FreeleyDiesWhenHeIsKilled",      "InvPeopleDie"},
        {"FreeleyDieParticle",     "FreeleyDiePulse",     "FreeleyDiesWhenHeIsKilled",      "InvPeopleDie"},
        {"FreeleyDieParticle",     "FreeleyDiePulse",     "FreeleyDiesWhenHeIsKilled",      "InvPeopleDie"},
        {"FreeleyDieParticle",     "FreeleyDiePulse",     "FreeleyDiesWhenHeIsKilled",      "InvPeopleDie"},
    },
    {{"BlakeDieParticle",          "BlakeDiePulse",       "BlakeDiesWhenHeIsKilled",        "InvPeopleDie"}},
    {{"CalebDieParticle",          "CalebDiePulse",       "CalebDiesWhenHeIsKilled",        "InvPeopleDie"}},
    {{"StrifeguyDieParticle",      "StrifeguyDiePulse",   "StrifeguyDiesWhenHeIsKilled",    "InvPeopleDie"}},
    {
        {"EleenaDieParticle",      "EleenaDiePulse",      "EleenaDiesWhenSheIsKilled",      "InvPeopleDie"},
        {"EleenaDieParticle",      "EleenaDiePulse",      "EleenaDiesWhenSheIsKilled",      "InvPeopleDie"},
        {"EleenaDieParticle",      "EleenaDiePulse",      "EleenaDiesWhenSheIsKilled",      "InvPeopleDie"},
        {"EleenaDieParticle",      "EleenaDiePulse",      "EleenaDiesWhenSheIsKilled",      "InvPeopleDie"},
    },
    {{"C7ClassDieParticle",        "C7ClassDiePulse",     "C7ClassDiesWhenHeIsKilled",      "InvPeopleDie"}},
    {{"RMRClassDieParticle",       "RMRClassDiePulse",    "RMRClassDiesWhenHeIsKilled",     "InvPeopleDie"}},
    {{"KatarnDieParticle",         "KatarnDiePulse",      "KatarnDiesWhenHeIsKilled",       "InvPeopleDie"}},
    {
        {"MoomanDieParticle",      "MoomanDiePulse",      "MoomanDiesWhenHeIsKilled",       "InvPeopleDie"},
        {"MoomanDieParticle",      "MoomanDiePulse",      "MoomanDiesWhenHeIsKilled",       "InvPeopleDie"},
        {"MoomanDieParticle",      "MoomanDiePulse",      "MoomanDiesWhenHeIsKilled",       "InvPeopleDie"},
        {"MoomanDieParticle",      "MoomanDiePulse",      "MoomanDiesWhenHeIsKilled",       "InvPeopleDie"},
        {"MoomanDieParticle",      "MoomanDiePulse",      "MoomanDiesWhenHeIsKilled",       "InvPeopleDie"},
    },
    {{"JackDieParticle",           "JackDiePulse",        "JackDiesWhenHeIsKilled",         "InvPeopleDie"}},
    {{"GrondovalDieParticle",      "GrondovalDiePulse",   "GrondovalDiesWhenHeIsKilled",    "InvPeopleDie"}},
    {
        {"FreemanDieParticle",     "FreemanDiePulse",     "FreemanDiesWhenHeIsKilled",      "InvPeopleDie"},
        {"FreemanDieParticle",     "FreemanDiePulse",     "FreemanDiesWhenHeIsKilled",      "InvPeopleDie"},
    },
    {{"WangDieParticle",           "WangDiePulse",        "WangDiesWhenHeIsKilled",         "InvPeopleDie"}},
    {{"CybermageDieParticle",      "CybermageDiePulse",   "CybermageDiesWhenHeIsKilled",    "InvPeopleDie"}},
    {{"JonDieParticle",            "JonDiePulse",         "JonDiesWhenHeIsKilled",          "InvPeopleDie"}},
    {{"LeonardDieParticle",        "LeonardDiePulse",     "LeonardDiesWhenHeIsKilled",      "InvPeopleDie"}},
    {{"BittermanDieParticle",      "BittermanDiePulse",   "BittermanDiesWhenHeIsKilled",    "InvPeopleDie"}},
    {{"DemonessDieParticle",       "DemonessDiePulse",    "DemonessDiesWhenSheIsKilled",    "InvPeopleDie"}},
    {
        {"BondDieParticle",        "BondDiePulse",        "BondDiesWhenHeIsKilled",         "InvPeopleDie"},
        {"BondDieParticle",        "BondDiePulse",        "BondDiesWhenHeIsKilled",         "InvPeopleDie"},
    },
    {{"PettonDieParticle",         "PettonDiePulse",      "PettonDiesWhenHeIsKilled",       "InvPeopleDie"}},
    {{"DanielDieParticle",         "DanielDiePulse",      "DanielDiesWhenHeIsKilled",       "InvPeopleDie"}},
    {{"Prisoner849DieParticle",    "Prisoner849DiePulse", "Prisoner849DiesWhenSheIsKilled", "InvPeopleDie"}},
    {{"RTCWBlazkoDieParticle",     "RTCWBlazkoDiePulse",  "RTCWBlazkoDiesWhenHeIsKilled",   "InvPeopleDie"}},
    {{"SargeDieParticle",          "SargeDiePulse",       "SargeDiesWhenHeIsKilled",        "InvPeopleDie"}},
    {{"PyroGXDieParticle",         "PyroGXDiePulse",      "PyroGXDiesWhenItIsKilled",       "InvPeopleDie"}},
    {{"JCDentonDieParticle",       "JCDentonDiePulse",    "JCDentonDiesWhenHeIsKilled",     "InvPeopleDie"}},
};

#define ARMORCOUNT 17

#define ARMOR_BONUS1          0
#define ARMOR_MAXBONUS1       1
#define ARMOR_BONUS5          2
#define ARMOR_BONUS25         3
#define ARMOR_BONUS50         4
#define ARMOR_GREEN           5
#define ARMOR_YELLOW          6
#define ARMOR_BLUE            7
#define ARMOR_BLUE_WITHYELLOW 8
#define ARMOR_RED             9
#define ARMOR_SILVER          10
#define ARMOR_MEGASPHERE      11
#define ARMOR_LMSARMOR1       12
#define ARMOR_LMSARMOR2       13
#define ARMOR_LMSARMOR3       14
#define ARMOR_LMSARMOR4       15
#define ARMOR_LMSARMOR5       16

int ArmorPickups[ARMORCOUNT] = 
{
    "ArmorScrap",
    "MaxArmorScrap",
    "ArmorScrapDump",
    "ArmorPackBonusLight",
    "ArmorPackBonusHeavy",
    "ArmorPack1",
    "ArmorPack2",
    "ArmorPack3",
    "ArmorPack3",
    "ArmorPack4",
    "ArmorPack5",
    "MegaPack",
    // The following are for LMS and are not actually meant to be spawned
    "",
    "",
    "",
    "",
    "",
};

int ArmorItems[ARMORMODES][ARMORCOUNT] = 
{
    {
        "ArmorScrapArmorNormal",
        "MaxArmorScrapArmorNormal",
        "ArmorScrapDumpArmorNormal",
        "ArmorPackBonusLightArmorNormal",
        "ArmorPackBonusHeavyArmorNormal",
        "ArmorPack1ArmorNormal",
        "ArmorPack2ArmorNormal",
        "ArmorPack3ArmorNormal",
        "ArmorPack3ArmorNormal",
        "ArmorPack4ArmorNormal",
        "ArmorPack5ArmorNormal",
        "ArmorPack3ArmorNormal",
        "ArmorPack1ArmorNormal",
        "ArmorPack2ArmorNormal",
        "ArmorPack3ArmorNormal",
        "ArmorPack4ArmorNormal",
        "ArmorPack5ArmorNormal",
    },
    {
        "ArmorScrapArmorQuake",
        "MaxArmorScrapArmorQuake",
        "ArmorScrapDumpArmorQuake",
        "ArmorPackBonusLightArmorQuake",
        "ArmorPackBonusHeavyArmorQuake",
        "ArmorPack1ArmorQuake",
        "ArmorPack2ArmorQuake",
        "ArmorPack2ArmorQuake",
        "ArmorPack3ArmorQuake",
        "ArmorPack4ArmorQuake",
        "ArmorPack5ArmorQuake",
        "ArmorPack3ArmorQuake",
        "ArmorPack1ArmorQuake",
        "ArmorPack2ArmorQuake",
        "ArmorPack3ArmorQuake",
        "ArmorPack4ArmorQuake",
        "ArmorPack5ArmorQuake",
    },
    {
        "ArmorScrapArmorQuakePlus",
        "MaxArmorScrapArmorQuakePlus",
        "ArmorScrapDumpArmorQuakePlus",
        "ArmorPackBonusLightArmorQuakePlus",
        "ArmorPackBonusHeavyArmorQuakePlus",
        "ArmorPack2ArmorQuake",
        "ArmorPack2ArmorQuake",
        "ArmorPack3ArmorQuake",
        "ArmorPack3ArmorQuake",
        "ArmorPack4ArmorQuake",
        "ArmorPack5ArmorQuake",
        "ArmorPack3ArmorQuake",
        "ArmorPack1ArmorQuake",
        "ArmorPack2ArmorQuake",
        "ArmorPack3ArmorQuake",
        "ArmorPack4ArmorQuake",
        "ArmorPack5ArmorQuake",
    },
    {
        "ArmorScrapArmorMarathon",
        "MaxArmorScrapArmorMarathon",
        "ArmorScrapDumpArmorMarathon",
        "ArmorPackBonusLightArmorMarathon",
        "ArmorPackBonusHeavyArmorMarathon",
        "ArmorPack1ArmorMarathon",
        "ArmorPack2ArmorMarathon",
        "ArmorPack3ArmorMarathon",
        "ArmorPack3ArmorMarathon",
        "ArmorPack4ArmorMarathon",
        "ArmorPack5ArmorMarathon",
        "ArmorPack5ArmorMarathon",
        "ArmorPack1ArmorMarathon",
        "ArmorPack2ArmorMarathon",
        "ArmorPack3ArmorMarathon",
        "ArmorPack4ArmorMarathon",
        "ArmorPack5ArmorMarathon",
    },
    {
        "ArmorScrapArmorHeretic",
        "MaxArmorScrapArmorHeretic",
        "ArmorScrapDumpArmorHeretic",
        "ArmorPackBonusLightArmorHeretic",
        "ArmorPackBonusHeavyArmorHeretic",
        "ArmorPack1ArmorHeretic",
        "ArmorPack2ArmorHeretic",
        "ArmorPack3ArmorHeretic",
        "ArmorPack3ArmorHeretic",
        "ArmorPack4ArmorHeretic",
        "ArmorPack5ArmorHeretic",
        "ArmorPack3ArmorHeretic",
        "ArmorPack1ArmorHeretic",
        "ArmorPack2ArmorHeretic",
        "ArmorPack3ArmorHeretic",
        "ArmorPack4ArmorHeretic",
        "ArmorPack5ArmorHeretic",
    },
    {
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
        "NoArmor",
    },
};

int ArmorAmounts[ARMORMODES][ARMORCOUNT][5] = 
{
    {
        {1,   200, 33,  0, 0},
        {1,   200, 33,  1, 50},
        {5,   200, 33,  0, 0},
        {25,  200, 33,  0, 0},
        {50,  300, 33,  0, 0},
        {100, 100, 33,  0, 0},
        {150, 150, 40,  0, 0},
        {200, 200, 50,  0, 0},
        {200, 200, 50,  0, 0},
        {250, 250, 66,  0, 0},
        {300, 300, 100, 0, 0},
        {200, 200, 50,  0, 0},
        {100, 100, 33,  0, 0},
        {150, 150, 40,  0, 0},
        {200, 200, 50,  0, 0},
        {250, 250, 66,  0, 0},
        {300, 300, 100, 0, 0},
    },
    {
        {1,   200, 30,  0, 0},
        {1,   200, 30,  1, 50},
        {5,   200, 30,  0, 0},
        {25,  200, 30,  0, 0},
        {50,  300, 30,  0, 0},
        {100, 100, 30,  0, 0},
        {150, 150, 60,  0, 0},
        {150, 150, 60,  0, 0},
        {200, 200, 80,  0, 0},
        {250, 250, 90,  0, 0},
        {300, 300, 100, 0, 0},
        {200, 200, 80,  0, 0},
        {100, 100, 30,  0, 0},
        {150, 150, 60,  0, 0},
        {200, 200, 80,  0, 0},
        {250, 250, 90,  0, 0},
        {300, 300, 100, 0, 0},
    },
    {
        {1,   200, 60,  0, 0},
        {1,   200, 60,  1, 50},
        {5,   200, 60,  0, 0},
        {25,  200, 60,  0, 0},
        {50,  300, 60,  0, 0},
        {150, 150, 60,  0, 0},
        {150, 150, 60,  0, 0},
        {200, 200, 80,  0, 0},
        {200, 200, 80,  0, 0},
        {250, 250, 90,  0, 0},
        {300, 300, 100, 0, 0},
        {200, 200, 80,  0, 0},
        {100, 100, 30,  0, 0},
        {150, 150, 60,  0, 0},
        {200, 200, 80,  0, 0},
        {250, 250, 90,  0, 0},
        {300, 300, 100, 0, 0},
    },
    {
        {1,   200, 100, 0, 0},
        {1,   200, 100, 1, 50},
        {5,   200, 100, 0, 0},
        {25,  200, 100, 0, 0},
        {50,  300, 100, 0, 0},
        {100, 100, 100, 0, 0},
        {150, 150, 100, 0, 0},
        {200, 200, 100, 0, 0},
        {200, 200, 100, 0, 0},
        {250, 250, 100, 0, 0},
        {300, 300, 100, 0, 0},
        {300, 300, 100, 0, 0},
        {100, 100, 100, 0, 0},
        {150, 150, 100, 0, 0},
        {200, 200, 100, 0, 0},
        {250, 250, 100, 0, 0},
        {300, 300, 100, 0, 0},
    },
    {
        {1,   200, 50,  0, 0},
        {1,   200, 50,  1, 50},
        {5,   200, 50,  0, 0},
        {25,  200, 50,  0, 0},
        {50,  300, 50,  0, 0},
        {100, 100, 50,  0, 0},
        {150, 150, 67,  0, 0},
        {200, 200, 75,  0, 0},
        {200, 200, 75,  0, 0},
        {250, 250, 87,  0, 0},
        {300, 300, 100, 0, 0},
        {200, 200, 75,  0, 0},
        {100, 100, 50,  0, 0},
        {150, 150, 67,  0, 0},
        {200, 200, 75,  0, 0},
        {250, 250, 87,  0, 0},
        {300, 300, 100, 0, 0},
    },
    {
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0},
    },
};

int ArmorModeNames[ARMORMODES] = 
{
    "Normal",
    "Quake",
    "Quake+",
    "Marathon",
    "Heretic",
    "None",
};

str BanCVarsAndStrings[CLASSCOUNT][MAXMODES][2] =
{
    {
        {"samsara_bandoomguy",          "\c[M7]Doomguy (Original) is currently banned from play.\c-"},
        {"samsara_bandoomguy64",        "\c[M7]Doom 64 Guy is currently banned from play.\c-"},
        {"samsara_bandoomguystr",       "\c[M7]Doomguy (Stronghold) is currently banned from play.\c-"},
    },
    {{"samsara_banchex",                "\c[M7]Chex Warrior is currently banned from play.\c-"}},
    {{"samsara_bancorvus",              "\c[M7]Corvus is currently banned from play.\c-"}},
    {
        {"samsara_banbj",               "\c[M7]B.J. Blazkowicz (Original) is currently banned from play.\c-"},
        {"samsara_banbjlost",           "\c[M7]B.J. Blazkowicz (Lost Episodes) is currently banned from play.\c-"},
        {"samsara_banbjctk",            "\c[M7]B.J. Blazkowicz (Castle Totenkopf SDL) is currently banned from play.\c-"},
    },
    {
        {"samsara_banparias",           "\c[M7]Parias (Reincarnation) is currently banned from play.\c-"},
        {"samsara_banpariasclassic",    "\c[M7]Parias (Classic) is currently banned from play.\c-"},
        {"samsara_bandaedolon",         "\c[M7]Daedolon is currently banned from play.\c-"},
        {"samsara_banbaratus",          "\c[M7]Baratus is currently banned from play.\c-"},
    },
    {
        {"samsara_banduke",             "\c[M7]Duke Nukem (Original) is currently banned from play.\c-"},
        {"samsara_bandukelab",          "\c[M7]Duke Nukem (Life's a Beach) is currently banned from play.\c-"},
        {"samsara_banduke64",           "\c[M7]Duke Nukem (Duke Nukem 64) is currently banned from play.\c-"},
    },
    {{"samsara_banso",                  "\c[M7]Security Officer is currently banned from play.\c-"}},
    {{"samsara_banranger",              "\c[M7]Ranger is currently banned from play.\c-"}},
    {
        {"samsara_banfreely",           "\c[M7]Ian Paul Freeley is currently banned from play.\c-"},
        {"samsara_bancassatt",          "\c[M7]Taradino Cassatt is currently banned from play.\c-"},
        {"samsara_banbarrett",          "\c[M7]Thi Barrett is currently banned from play.\c-"},
        {"samsara_banni",               "\c[M7]Lorelei Ni is currently banned from play.\c-"},
        {"samsara_banwendt",            "\c[M7]Doug Wendt is currently banned from play.\c-"},
    },
    {{"samsara_banblake",               "\c[M7]Blake Stone is currently banned from play.\c-"}},
    {{"samsara_bancaleb",               "\c[M7]Caleb is currently banned from play.\c-"}},
    {{"samsara_banstrifeguy",           "\c[M7]Strifeguy is currently banned from play.\c-"}},
    {
        {"samsara_baneleena",           "\c[M7]Eleena Brynstaarl is currently banned from play.\c-"},
        {"samsara_bankamchak",          "\c[M7]Kamchak is currently banned from play.\c-"},
        {"samsara_bandanblaze",         "\c[M7]Dan Blaze is currently banned from play.\c-"},
        {"samsara_banalliancecommando", "\c[M7]Alliance Commando is currently banned from play.\c-"},
    },
    {{"samsara_banspaceseal",           "\c[M7]Space Seal is currently banned from play.\c-"}},
    {{"samsara_banrebelmooncommando",   "\c[M7]LDF Commando is currently banned from play.\c-"}},
    {{"samsara_bankatarn",              "\c[M7]Kyle Katarn is currently banned from play.\c-"}},
    {
        {"samsara_banmooman",           "\c[M7]Aldus Kaden is currently banned from play.\c-"},
        {"samsara_bancyborg",           "\c[M7]Tobias Locke is currently banned from play.\c-"},
        {"samsara_banlizardman",        "\c[M7]Xith is currently banned from play.\c-"},
        {"samsara_banmutant",           "\c[M7]Specimen 7 is currently banned from play.\c-"},
        {"samsara_bandominatrix",       "\c[M7]Theola Nom is currently banned from play.\c-"},
    },
    {{"samsara_bandisruptor",           "\c[M7]Jack Curtis is currently banned from play.\c-"}},
    {{"samsara_bangrondoval",           "\c[M7]Grondoval is currently banned from play.\c-"}},
    {
        {"samsara_banfreeman",          "\c[M7]Gordon Freeman is currently banned from play.\c-"},
        {"samsara_banshephard",         "\c[M7]Adrian Shephard is currently banned from play.\c-"},
    },
    {{"samsara_banwang",                "\c[M7]Lo Wang is currently banned from play.\c-"}},
    {{"samsara_bancm",                  "\c[M7]CyberMage is currently banned from play.\c-"}},
    {{"samsara_banjon",                 "\c[M7]Jon P. is currently banned from play.\c-"}},
    {{"samsara_banrr",                  "\c[M7]Leonard is currently banned from play.\c-"}},
    {{"samsara_banq2",                  "\c[M7]Bitterman is currently banned from play.\c-"}},
    {{"samsara_bandemoness",            "\c[M7]Demoness is currently banned from play.\c-"}},
    {
        {"samsara_banbond",             "\c[M7]James Bond (GoldenEye 007) is currently banned from play.\c-"},
        {"samsara_banbondgf",           "\c[M7]James Bond (Goldfinger 64) is currently banned from play.\c-"},
    },
    {{"samsara_banpetton",              "\c[M7]Petton Everhail is currently banned from play.\c-"}},
    {{"samsara_bandaniel",              "\c[M7]Daniel Garner is currently banned from play.\c-"}},
    {{"samsara_banprisoner",            "\c[M7]Prisoner 849 is currently banned from play.\c-"}},
    {{"samsara_banrtcw",                "\c[M7]B.J. Blazkowicz (Return to Castle Wolfenstein) is currently banned from play.\c-"}},
    {{"samsara_bansarge",               "\c[M7]Sarge is currently banned from play.\c-"}},
    {{"samsara_banpyrogx",              "\c[M7]Pyro-GX is currently banned from play.\c-"}},
    {{"samsara_banjcdenton",            "\c[M7]JC Denton is currently banned from play.\c-"}},
};


#define DAMAGEDEFENSEMODES 31
#define DAMAGEDEFENSEZEROINDEX 10

#define SPEEDMODES 17
#define SPEEDZEROINDEX 6

str DamageAndDefenseCVars[CLASSCOUNT][MAXMODES][2] = 
{
    {
        {"samsara_doomguydamage",          "samsara_doomguydefense"},
        {"samsara_doomguy64damage",        "samsara_doomguy64defense"},
        {"samsara_doomguystrdamage",       "samsara_doomguystrdefense"},
    },
    {{"samsara_chexdamage",                "samsara_chexdefense"}},
    {{"samsara_corvusdamage",              "samsara_corvusdefense"}},
    {
        {"samsara_bjdamage",               "samsara_bjdefense"},
        {"samsara_bjlostdamage",           "samsara_bjlostdefense"},
        {"samsara_bjctkdamage",            "samsara_bjctkdefense"},
    },
    {
        {"samsara_pariasdamage",           "samsara_pariasdefense"},
        {"samsara_pariasclassicdamage",    "samsara_pariasclassicdefense"},
        {"samsara_daedolondamage",         "samsara_daedolondefense"},
        {"samsara_baratusdamage",          "samsara_baratusdefense"},
    },
    {
        {"samsara_dukedamage",             "samsara_dukedefense"},
        {"samsara_dukelabdamage",          "samsara_dukelabdefense"},
        {"samsara_duke64damage",           "samsara_duke64defense"},
    },
    {{"samsara_sodamage",                  "samsara_sodefense"}},
    {{"samsara_rangerdamage",              "samsara_rangerdefense"}},
    {
        {"samsara_freelydamage",           "samsara_freelydefense"},
        {"samsara_cassattdamage",          "samsara_cassattdefense"},
        {"samsara_barrettdamage",          "samsara_barrettdefense"},
        {"samsara_nidamage",               "samsara_nidefense"},
        {"samsara_wendtdamage",            "samsara_wendtdefense"},
    },
    {{"samsara_blakedamage",               "samsara_blakedefense"}},
    {{"samsara_calebdamage",               "samsara_calebdefense"}},
    {{"samsara_strifeguydamage",           "samsara_strifeguydefense"}},
    {
        {"samsara_eleenadamage",           "samsara_eleenadefense"},
        {"samsara_kamchakdamage",          "samsara_kamchakdefense"},
        {"samsara_danblazedamage",         "samsara_danblazedefense"},
        {"samsara_alliancecommandodamage", "samsara_alliancecommandodefense"},
    },
    {{"samsara_spacesealdamage",           "samsara_spacesealdefense"}},
    {{"samsara_rebelmooncommandodamage",   "samsara_rebelmooncommandodefense"}},
    {{"samsara_katarndamage",              "samsara_katarndefense"}},
    {
        {"samsara_moomandamage",           "samsara_moomandefense"},
        {"samsara_cyborgdamage",           "samsara_cyborgdefense"},
        {"samsara_lizardmandamage",        "samsara_lizardmandefense"},
        {"samsara_mutantdamage",           "samsara_mutantdefense"},
        {"samsara_dominatrixdamage",       "samsara_dominatrixdefense"},
    },
    {{"samsara_disruptordamage",           "samsara_disruptordefense"}},
    {{"samsara_grondovaldamage",           "samsara_grondovaldefense"}},
    {
        {"samsara_freemandamage",          "samsara_freemandefense"},
        {"samsara_shepharddamage",         "samsara_shepharddefense"},
    },
    {{"samsara_wangdamage",                "samsara_wangdefense"}},
    {{"samsara_cmdamage",                  "samsara_cmdefense"}},
    {{"samsara_jondamage",                 "samsara_jondefense"}},
    {{"samsara_rrdamage",                  "samsara_rrdefense"}},
    {{"samsara_q2damage",                  "samsara_q2defense"}},
    {{"samsara_demonessdamage",            "samsara_demonessdefense"}},
    {
        {"samsara_bonddamage",             "samsara_bonddefense"},
        {"samsara_bondgfdamage",           "samsara_bondgfdefense"},
    },
    {{"samsara_pettondamage",              "samsara_pettondefense"}},
    {{"samsara_danieldamage",              "samsara_danieldefense"}},
    {{"samsara_prisonerdamage",            "samsara_prisonerdefense"}},
    {{"samsara_rtcwdamage",                "samsara_rtcwdefense"}},
    {{"samsara_sargedamage",               "samsara_sargedefense"}},
    {{"samsara_pyrogxdamage",              "samsara_pyrogxdefense"}},
    {{"samsara_jcdentondamage",            "samsara_jcdentondefense"}},
};

str CVarDamageAndDefenseItems[DAMAGEDEFENSEMODES][2] = 
{
    {"PowerDamageBuff-10", "PowerDefenseBuff-10"},
    {"PowerDamageBuff-9",  "PowerDefenseBuff-9"},
    {"PowerDamageBuff-8",  "PowerDefenseBuff-8"},
    {"PowerDamageBuff-7",  "PowerDefenseBuff-7"},
    {"PowerDamageBuff-6",  "PowerDefenseBuff-6"},
    {"PowerDamageBuff-5",  "PowerDefenseBuff-5"},
    {"PowerDamageBuff-4",  "PowerDefenseBuff-4"},
    {"PowerDamageBuff-3",  "PowerDefenseBuff-3"},
    {"PowerDamageBuff-2",  "PowerDefenseBuff-2"},
    {"PowerDamageBuff-1",  "PowerDefenseBuff-1"},
    {"",                   ""}, // middle point
    {"PowerDamageBuff1",   "PowerDefenseBuff1"},
    {"PowerDamageBuff2",   "PowerDefenseBuff2"},
    {"PowerDamageBuff3",   "PowerDefenseBuff3"},
    {"PowerDamageBuff4",   "PowerDefenseBuff4"},
    {"PowerDamageBuff5",   "PowerDefenseBuff5"},
    {"PowerDamageBuff6",   "PowerDefenseBuff6"},
    {"PowerDamageBuff7",   "PowerDefenseBuff7"},
    {"PowerDamageBuff8",   "PowerDefenseBuff8"},
    {"PowerDamageBuff9",   "PowerDefenseBuff9"},
    {"PowerDamageBuff10",  "PowerDefenseBuff10"},
    {"PowerDamageBuff11",  "PowerDefenseBuff11"},
    {"PowerDamageBuff12",  "PowerDefenseBuff12"},
    {"PowerDamageBuff13",  "PowerDefenseBuff13"},
    {"PowerDamageBuff14",  "PowerDefenseBuff14"},
    {"PowerDamageBuff15",  "PowerDefenseBuff15"},
    {"PowerDamageBuff16",  "PowerDefenseBuff16"},
    {"PowerDamageBuff17",  "PowerDefenseBuff17"},
    {"PowerDamageBuff18",  "PowerDefenseBuff18"},
    {"PowerDamageBuff19",  "PowerDefenseBuff19"},
    {"PowerDamageBuff20",  "PowerDefenseBuff20"},
};

str CVarSpeedItems[SPEEDMODES] = 
{
    "PowerSpeedBuff-6",
    "PowerSpeedBuff-5",
    "PowerSpeedBuff-4",
    "PowerSpeedBuff-3",
    "PowerSpeedBuff-2",
    "PowerSpeedBuff-1",
    "", // middle point
    "PowerSpeedBuff1",
    "PowerSpeedBuff2",
    "PowerSpeedBuff3",
    "PowerSpeedBuff4",
    "PowerSpeedBuff5",
    "PowerSpeedBuff6",
    "PowerSpeedBuff7",
    "PowerSpeedBuff8",
    "PowerSpeedBuff9",
    "PowerSpeedBuff10",
};

int SpeedModeNames[SPEEDMODES] = 
{
    "Immobile",
    "Almost Immobile",
    "Extremely Slow",
    "Slower",
    "Slow",
    "Slightly Slow",
    "Normal",
    "Slightly Fast",
    "Fast",
    "Faster",
    "Doubled",
    "Quadrupled",
    "Extremely Fast",
    "Uncontrollable",
    "Insane",
    "AAAAAAAAAAAAAAAAHHH",
    "FOR THE LOVE OF GOD PLEASE SLOW DOWN",
};

int array_wolfmove[PLAYERMAX];
int array_smoothAnim[PLAYERMAX];
int array_ballgag[PLAYERMAX];
int array_weaponBar[PLAYERMAX];
int array_pickupswitch[PLAYERMAX];
int ServerEnterTimes[PLAYERMAX];
int WolfenEnterTimes[PLAYERMAX];
int ClientEnterTimes[PLAYERMAX];
int ResonantTimes[PLAYERMAX][RESCOUNT];
int ScheduledTimes[PLAYERMAX][3];
int playerClasses[PLAYERMAX] = {-1};
int playerClassesClient[PLAYERMAX] = {-1};
int loadoutPrevValue[PLAYERMAX][SLOTCOUNT + UNIQUECOUNT];

int SamsaraWepType, SamsaraClientClass, SamsaraItemFlash, SamsaraAlternativeClass;
int SamsaraEquipmentLoadout[SLOTCOUNT + UNIQUECOUNT];
int SamsaraClientWeps[SLOTCOUNT] = {0};
int SamsaraClientWepFlashes[SLOTCOUNT] = {0};
int IsServer = 0;
int UnloadingNow = 0;
int ArmorMode = -1;
int MapArmors[ARMORCOUNT] = {-1};
bool MapRevealerPickedUp = false;

global int 0:SamsaraGlobal[];
